### ISSUE TITLE
docker-compose build not working

### ISSUE THREAD

**Issue by dimitriacosta** [instructure/canvas-lms#1048]
### Summary:
Every time I try to run the docker-compose file from this repo it gets stuck on set 24/26 for a long time (some times even hours), if I try to view the logs of the running container, it shows nothing

### Steps to reproduce:

 1. Download the repo 
 2. Checkout the stable branch
 3. Run `docker-compose build`

### Expected behavior:
Creates all needed images

<img width="1593" alt="screen shot 2017-06-01 at 11 33 16 am" src="https://cloud.githubusercontent.com/assets/5995547/26692669/c17427be-46be-11e7-8e3b-34ec2cf473c4.png">

<img width="1150" alt="screen shot 2017-06-01 at 11 38 41 am" src="https://cloud.githubusercontent.com/assets/5995547/26692726/f348eb30-46be-11e7-83a0-071bd1b511d9.png">

**Comment by jenseng** [comment]
@dimitriacosta we have an internal (jenkins) build that does this as well on every commit, and it doesn't get stuck on this step. Can you provide some more information, such as:

1. what version of docker?
2. what flavor of linux is the host OS, and which kernel?
3. how much RAM do you have?
4. how much free space do you have?

You might also try running off the master branch to see if you get a different result; we recently made some changes to the Dockerfile to get the layer sizes smaller. That said, it's surprising that you'd repeatedly see it getting stuck on that step.

**Comment by dimitriacosta** [comment]
Thanks for your quick answer @jenseng, this is my compute's information

1. I'm using docker 17.03.1-ce
<img width="364" alt="screen shot 2017-06-01 at 12 09 50 pm" src="https://cloud.githubusercontent.com/assets/5995547/26694254/111e2242-46c4-11e7-821e-46725bfb323a.png">


2. I'm on a Mac with macOS Sierra 10.12.5
![screen shot 2017-06-01 at 12 11 31 pm](https://cloud.githubusercontent.com/assets/5995547/26694247/0abf9368-46c4-11e7-8f85-06686fa1f3fa.png)


3. I have 8GB of RAM and Docker is using 2GB
![screen shot 2017-06-01 at 12 12 11 pm](https://cloud.githubusercontent.com/assets/5995547/26694108/9f774524-46c3-11e7-8831-01aa1eb4fb62.png)

4. I have 103GB of free space on my HD
![screen shot 2017-06-01 at 12 13 11 pm](https://cloud.githubusercontent.com/assets/5995547/26694160/c56765de-46c3-11e7-9ec4-48fb85b36dbd.png)

I haven't try with the master branch yet but I'll take a look

**Comment by jenseng** [comment]
I'll see if I can reproduce the problem under Docker for Mac ... it works fine on my mac using virtualbox + dinghy + homebrewed docker

**Comment by grahamb** [comment]
I've had no luck using the official Docker for Mac. Dinghy is aces.

**Comment by dimitriacosta** [comment]
I also tried on an ubuntu box with vagrant and it didn't work either

**Comment by dimitriacosta** [comment]
I switched to the master branch and now I can build the project but when I run this command `docker-compose run --rm web bash -c "bundle install"` (as seen in here https://github.com/instructure/canvas-lms/blob/stable/doc/docker/README.md) I get something like this

![screen shot 2017-06-13 at 12 03 06 pm](https://user-images.githubusercontent.com/5995547/27097086-59b40ef2-5030-11e7-86c2-c53ba2e17bae.png)

**Comment by CullenShane** [comment]
I am also having this issue on Docker on Mac.  I left it to build for 24 + hours and finally generated an error message: 

WARN: Side effects in initialization of unused variable string [0:1935,4]
WARN: Side effects in initialization of unused variable borders [0:2793,6]
ERROR: Service 'web' failed to build: {u'stream': u'\x1b[91mWARN: Side effects in initialization of unused variable borders [0:2793,6]\n\x1b[0m'}

stable is broken because of people-mozilla being gone, but cherry-picking the fix for that issue into stable from master also produces the same hang.  Master also hangs for me on official Docker.

Is there a work around?

**Comment by tierra** [comment]
We highly recommend using Dinghy with VirtualBox, and installing Docker from brew on OSX, rather than using Docker for Mac or the old Docker Toolbox:
https://github.com/instructure/canvas-lms/blob/master/doc/docker/getting_docker.md

If you switch, you'll need to uninstall Docker for Mac.

That said, building the Canvas LMS docker image requires a significant amount of RAM, which needs to be allocated to your docker VM on OSX, and at a minimum, it should be 4GB. This corresponds with the same minimum requirements for running Canvas on a server, and is specifically necessary for successfully compiling Canvas assets, which appears to be where your build is failing right now. Anything you can do in order to allocate more RAM for this task should help you here.

**Comment by CullenShane** [comment]
Thanks so much for your reply, I tried increasing the RAM that Docker was assigned (I wasn't aware there was a setting) from 2GB to 6GB and the build completed successfully.

![image](https://user-images.githubusercontent.com/597786/28075548-6b34befe-6621-11e7-9de6-ca6313eeea54.png)
