### ISSUE TITLE
courses/:course_id/users API endpoint doesn't return email addresses

### ISSUE THREAD

**Issue by wolever** [instructure/canvas-lms#1050]
Some time last week I noticed that the `api/v1/courses/:course_id/users? enrollment_type=student&include=email` endpoint had stopped returning student email addresses.

This is not (obviously) a permission issue, as the email is still returned by `api/v1/users/:user_id/profile`.

This is testing against the current production version hosted on instructure.com.

**Comment by wolever** [comment]
I've tested with the most recent commit in stable (b84306350d74f8f7da24b09cf051bebb84f6c644) and emails seem to be returned.

One thing I noticed which *might* be related: if students are enrolled in a course but their enrolment has not been confirmed, then their email and SIS id aren't included in `courses/:course_id/users`.

**Comment by ToeBee** [comment]
We talked about this on IRC yesterday a bit but just to put it here for posterity: the URL parameter should be `include[]=email`. There does seem to be some inconsistency with whether the `[]` is required or not. In our hosted Canvas instances it is absolutely required. Some people with self-hosted Canvas seem to be getting away without using it. However the docs do say to use it for items that can be specified multiple times with a list of values.

**Comment by davidfokkema** [comment]
I can confirm that on this endpoint email addresses are _not_ returned for users who haven't accepted their course invitations. However, if you get users via the sections endpoint with `include[]=students` and `include[]=email` then you _do_ get their email addresses. Since I want to email all students who have _not_ yet accepted their invitations, this is a pain. Consistency would be nice. Thanks!

**Comment by davidfokkema** [comment]
Please re-open this issue.
