### ISSUE TITLE
Can't set section integration_id

### ISSUE THREAD

**Issue by pauljarc** [instructure/canvas-lms#1154]
### Summary:

According to [the documentation](https://canvas.instructure.com/doc/api/sections.html#method.sections.update) and experiment, the API call to update or create a section does not allow us to set a section's integration_id, even though the integration_id exists as [documented in the call to get a section](https://canvas.instructure.com/doc/api/sections.html#method.sections.show).

### Steps to reproduce:

 1. Perform an API call to create or update a section, including course_section[integration_id] as one of the fields to set.
 2. Perform an API call to get the section.
 3. The section's integration_id is still null.

### Expected behavior:

The API should allow setting the integration_id for a section in create/update operations.

### Additional notes:

[SIS imports](https://canvas.instructure.com/doc/api/file.sis_csv.html) seem to allow setting integration_id for users, but not for anything else.

**Comment by omarkhan** [comment]
Thanks @pauljarc. We use github issues for bugs only, please submit feature requests on the [community site](https://community.canvaslms.com/community/ideas).

**Comment by pauljarc** [comment]
I don't quite understand how this is not a bug.  Are you saying that the current behavior, where the integration_id exists, but there's no way whatsoever to change it to anything non-null, is intentional?  I don't see how it could serve any useful purpose as it is.  That's why I submitted this as a bug.

**Comment by ccutrer** [comment]
integration_id _can_ be set via an SIS Import (thought it may be undocumented). Originally integration_id was only intended for a specific integration for a specific partner, but it has slowly grown to become useful to many users, so it has been slowly added to additional API endpoints and exposed in the UI as requested. So really we're splitting hairs at this point if an integration_id missing from a specific API is a feature request or a bug. Regardless, we'll get this one done real quick, since it's so easy to add, and there's no reason not to.

**Comment by pauljarc** [comment]
Thanks!  Updating the SIS import documentation would also be appreciated.

**Comment by roor0** [comment]
documentation was also added in 9077f36
