### ISSUE TITLE
'Grade' is the same as 'Points' in Grade View (On Student)

### ISSUE THREAD

**Issue by kirbykirby56** [instructure/canvas-lms#1155]
### Summary:
The 'Grade' category on the Student view for an assignment is the same as 'Points'.

### Steps to reproduce:
 1. Complete an assignment
 2. Recieve a grade
 3. View your grade

### Expected behavior:
All in all, this could be intentional, but I feel that the 'Grade' box is supposed to show a percentage grade based off of 'Points', e.g. 164/200 points = 82% grade. It also saves students time when glancing at their grades. Thanks!

### Additional Notes:
While this was observed on iOS, it's also weird that the Canvas website seems to have a similar problem. The 'Grade' on the Web version shows the 'points / max points' format as well. As a student, I would prefer seeing the Grade be a percentage, with maybe a Points text shown below it.
Here's a quick mockup.
**Grade:**  82%
_164/200_
or
**Grade:**  82%
**Points:** _164/200_

I'm not entirely sure if this would constitute a feature request, but seeing as it seems to be an issue on the iOS version, I decided an issue was probably the way to go.

**Comment by simonista** [comment]
Hey @kirbykirby56, this is actually a setting that teachers can set per-assignment, about whether they would like the grade to be displayed as points, percentage, or letter grade. See https://www.dropbox.com/s/ye2sxcgxs5jw5bc/Screenshot%202017-11-13%2011.59.14.png?dl=0.  Does that clarify the expected behavior?
