### ISSUE TITLE
Slideshares/slideshows not working

### ISSUE THREAD

**Issue by Gamewizard71** [instructure/canvas-lms#1194]
Summary:
Cannot view slideshare in module section
### Steps to reproduce:
 1. Enter modules
 2. Go to section with slideshare
 3. Slideshare is a greybox with no images

### Expected behavior:
Be able to view slideshare/slideshow
![screenshot_20180103-152242](https://user-images.githubusercontent.com/24537250/34544229-0865daca-f09a-11e7-8028-93f7f1f29846.jpg)

### Additional notes:
Canvas student app
Version 5.7.13
Android 7.1.1

**Comment by simonista** [comment]
Hi @Gamewizard71, it looks like you're having an issue with the android app. I think you're going to have better luck getting help by using the "Report a Problem" link in the help menu. See https://guides.instructure.com/m/18555/l/199459-how-do-i-get-help-with-the-canvas-student-app-on-my-android-device for details.

This issues board is primarily for users running the open source version of Canvas who are running into issues (which I'm guessing isn't your case, since you're using the android app), but the dedicated support line will get you a faster response for your specific issue.

Hope that helps!  Feel free to reopen if I'm made an incorrect assumption.
