### ISSUE TITLE
Unable to edit comments in discussions in app

### ISSUE THREAD

**Issue by Gamewizard71** [instructure/canvas-lms#1195]
### Summary:
Unabke to edit any comment published in discussions

### Steps to reproduce:
Pretty self explanatory. Feature is just not available.

### Expected behavior:
Ability to edit comments in discussion

### Additional notes:
Version 5.7.13
Android 7.1.1

**Comment by simonista** [comment]
Hi @Gamewizard71, it looks like you're having an issue with the android app. I think you're going to have better luck getting help by using the "Report a Problem" link in the help menu. See https://guides.instructure.com/m/18555/l/199459-how-do-i-get-help-with-the-canvas-student-app-on-my-android-device for details.

This issues board is primarily for users running the open source version of Canvas who are running into issues (which I'm guessing isn't your case, since you're using the android app), but the dedicated support line will get you a faster response for your specific issue.

Hope that helps!  Feel free to reopen if I'm made an incorrect assumption.
