### ISSUE TITLE
Unable to access appointment group through API

### ISSUE THREAD

**Issue by xcompass** [instructure/canvas-lms#1198]
### Summary:
To get a list of the appointment group, the server returns "[]" even though a group is manually created from web UI. To create a group through API, it returns unauthorized. (With bearer token, and the token works with other API calls)

### Steps to reproduce:

 1. create a appointment group through web UI and create a API access token
 2. call the following command:
```
curl https://[TEST_INSTANCE].instructure.com/api/v1/appointment_groups -H "Authorization: Bearer <TOKEN>"
```

### Expected behavior:
Return the group created through web UI.

### Additional notes:

**Comment by omarkhan** [comment]
The [appointment groups endpoint](https://canvas.instructure.com/doc/api/appointment_groups.html#method.appointment_groups.index) lists appointment groups that can be either reserved of managed by the requesting user. If you're using an API access token, the request will be made on behalf of the admin user that created the token. Since this user can neither reserve nor manage any appointment groups, the endpoint returns an empty list.

You can retrieve the appointment group by adding the `as_user_id` and `scope` request params:

```
curl 'https://<TEST_INSTANCE>.instructure.com/api/v1/appointment_groups?as_user_id=<TEACHER_ID>&scope=manageable' -H 'Authorization: Bearer <TOKEN>'
```

or

```
curl 'https://<TEST_INSTANCE>.instructure.com/api/v1/appointment_groups?as_user_id=<STUDENT_ID>' -H 'Authorization: Bearer <TOKEN>'
```
