### ISSUE TITLE
HEIC and JPEG images from iPhone handled improperly?

### ISSUE THREAD

**Issue by k4kfh** [instructure/canvas-lms#1206]
### Summary:

Either Canvas on the server or the iOS app is handling uploads of images improperly. When a teacher posts an image from an iPhone, it uploads using a .HEIC file extension, which is pretty poorly supported on most devices at this point. However, upon trying to feed the HEIC through a converter and get a JPEG, I discovered that the HEIC file Canvas gives is actually a JPEG. If you simply change the file extension to JPEG, it opens fine on any Windows PC.

### Steps to reproduce:

 1. Upload image from iphone
 2. Try to download image on Windows PC, and it won't know how to open it since it is a .HEIC
 3. Rename image.heic to image.jpeg, and Windows will open it just fine.

### Expected behavior:

If Canvas is trying to convert HEICs to JPEGs, it should actually change the file extension too. Otherwise, perhaps it should check the contents of the file and determine the correct extension that way.

### Additional notes:

**Comment by bootstraponline** [comment]
That's interesting. I've pinged the iOS team to see if they have any additional details to share.

**Comment by bootstraponline** [comment]
I checked with the team and it's a known issue. As a work around, you may try setting the iOS phone to Most Compatible.

<img src="https://user-images.githubusercontent.com/1173057/34846931-c25f13f8-f6e7-11e7-8fcb-a2ae50ef05ec.png" width="50%" />

I'm closing the issue here as it's unlikely to be resolved unless users continue to send feedback via the official support channels. We have an internal JIRA tracking the issue.
