### ISSUE TITLE
Canvas unable to submit file to assignment IF file name already matches file name of an already uploaded file

### ISSUE THREAD

**Issue by neilzxu** [instructure/canvas-lms#1226]
### Summary:
When submitting an assignment through the submit assignment process, one step requires to upload files. After clicking submit the page just greys out the submit button and sits there. This occurs when the filename of the uploaded file is the same as a file that is already in the uploaded files (my guess you need a file with the same name in the same course (so it's in the same folder) that has already been uploaded)

### Steps to reproduce:

 1.  Submit assignment by uploading file named "document.pdf" and submitting for a course.
 2.  Submit to a different assignment for the same course by uploading file named "document.pdf" (is a different file, but has same filename).

### Expected behavior:

It submits the document I uploaded to the assignment.

### Additional notes:

The second "document.pdf" gets successfully renamed and uploaded. It just doesn't get submitted to the assignment.

**Comment by neilzxu** [comment]
Might be the same issue as #1172

**Comment by mnicole** [comment]
This also happens when you're submitting a file to an exam, which is pretty stressful since it doesn't show any indication of the error or how to fix it. If this is intended functionality, the UI should show an error message.

**Comment by roor0** [comment]
I think this might be related to some different browser extensions or plugins. I have seen that this specifically causes an issue like that. https://chrome.google.com/webstore/detail/pop-up-blocker-for-chrome/bkkbcggnhapdmkeljlodobbkopceiche/related?hl=en

I am unable to reproduce the issue though.

**Comment by mnicole** [comment]
I do not have any ad or popup blocker extensions. Would an extension like that affect a second upload, or any file uploads in general? If uploading for the first time, it does successfully work. Last week, I was having the issue with any files uploaded with Chrome would time out, but this was different, the original files uploaded fine, and only a repeat did not work.

Several of my other classmates also reported it. I cannot test it on another browser because it was an exam and the exam is over. Thanks!
