### ISSUE TITLE
Incorrect example object for discussion posts in documentation

### ISSUE THREAD

**Issue by jessemcbride** [instructure/canvas-lms#1231]
### Summary:

Contrary to the example response in the [documentation](https://canvas.instructure.com/doc/api/discussion_topics.html), `require_initial_post` returns `null` when not set (instead of `false`).

### Steps to reproduce:

1. Request a discussion topic from the API.

### Expected behavior:

`require_initial_post` is `false`, not `null`.

**Comment by omarkhan** [comment]
Thanks for this @jessemcbride! I had a look through the specs for this. It looks like `require_initial_post` can be either `false` or `null`. I would suggest treating all falsey values as false here.

**Comment by liblit** [comment]
If the code is right, then [the documentation](https://canvas.instructure.com/doc/api/discussion_topics.html#DiscussionTopic) is wrong:

``` json
// If true then a user may not respond to other replies until that user has made an
// initial reply. Defaults to false.
"require_initial_post": false,
```

The comment reads “Defaults to **false**,” not “Defaults to null” or “Defaults to some unspecified falsey value.”

It may be wise to treat all falsey values as false here as @omarkhan suggests. But it is still the case that the documentation and the code disagree. One or the other is wrong.

**Comment by omarkhan** [comment]
You're right, it's not completely clear from the documentation. I'm reluctant to change the docs for this specific attribute though, because many other attributes work the same way (see the tests). I would prefer to update them all if possible. If you'd like to submit a pull request with updated documentation for this endpoint I will be happy to review it.
