### ISSUE TITLE
Empty list of unpublished courses

### ISSUE THREAD

**Issue by sefanja** [instructure/canvas-lms#1233]
### Summary:
`GET /api/v1/accounts/1/courses?state[]=unpublished` returns an empty list instead of a list of unpublished courses.

### Steps to reproduce:
 1. Create a new course (default workflow state will be 'unpublished')
 2. Go to `/api/v1/accounts/1/courses?state[]=unpublished`

### Expected behavior:
A list of unpublished courses.

The API does return these courses if I omit `?state[]=unpublished`.

### Additional notes:
Docs: https://canvas.instructure.com/doc/api/accounts.html#method.accounts.courses_api

**Comment by spencerolson** [comment]
Hi @sefanja , my guess is that you're not seeing that course in the response because the requesting user is not enrolled in the course. If you add the requesting user to the course (say, as a teacher), and then make that call, you should see the unpublished course get returned.

**Comment by omarkhan** [comment]
@sefanja did you try making the request as a user enrolled in the course?

**Comment by sefanja** [comment]
No, as a Canvas admin.

**Comment by omarkhan** [comment]
@sefanja please try it as a teacher enrolled in the course, as per @spencerolson's suggestion

**Comment by spencerolson** [comment]
Hey @sefanja sorry, I think i missed your follow-up comment. I can look into this when hitting the `api/v1/accounts/:id/courses` endpoint. I'll get back to you.

Thanks,
Spencer

**Comment by spencerolson** [comment]
Hi @sefanja OK, I think I've figured this one out. Long story short, it looks like you'll need to request states of `created` and `claimed`, instead of `unpublished`.

Per the documentation that you linked to, available values for state are: `[created, claimed, available, completed, deleted, all]`

This can be confusing, because as you mentioned, when omitting`?state[]=unpublished` and making the call to the endpoint, you get back an object with a `workflow_state` of `unpublished`, so you'd logically think you can request courses with state of `unpublished`. However, this is the code that is used to determine that return value of `unpublished` that you get back:

  ```
  def api_state
    return 'unpublished' if workflow_state == 'created' || workflow_state == 'claimed'
    workflow_state
  end
```

Essentially, in the cases where the course's workflow_state is "claimed" or "created", we return "unpublished" in the API response. So, with all that in mind, knowing that the unpublished course actually has a workflow_state of "claimed" or "created" (i believe in the example you mentioned the workflow_state will be "claimed"), you want to request `state`s of `claimed` and `created` to get unpublished courses.

Hope this helps!
Spencer

**Comment by sefanja** [comment]
Ah, unexpected indeed. Thank you for the clarification!

**Comment by spencerolson** [comment]
No worries! Glad we got it figured out. Sorry for that delay in response.
