### ISSUE TITLE
LTI request sends wrong login when user has multiple logins

### ISSUE THREAD

**Issue by christopher-b** [instructure/canvas-lms#1265]
### Summary:
Users with multiple logins sometimes have trouble launching LTI tools, because Canvas doesn't necessarily send the correct login in the LTI params. It appears that Canvas sends the login that was created most recently, rather than the login that the user actually used to log in. 

### Steps to reproduce:

 1. Create a user and add a second login to the user. Make sure both logins have SIS IDs. 
 2. Log in as the user with the original login. Launch an LTI tool and inspect the 'lis_person_sourcedid' LTI param that Canvas passes. 
 3. Log in using the second login. Launch an LTI tool and inspect the 'lis_person_sourcedid' param that Canvas passes. 

### Expected behaviour:
The lis_person_sourcedid param should match SIS id of login that was used to authenticate to Canvas. 

### Additional notes:
This makes it difficult for LTI tool providers to properly authenticate users with multiple logins.

**Comment by ccutrer** [comment]
It should be deterministic. It prefers a login that has an SIS ID, and if there are multiple it sorts them alphabetically and chooses the first one (not the most recent one). See https://github.com/instructure/canvas-lms/blob/stable/app/models/sis_pseudonym.rb.

**Comment by christopher-b** [comment]
Fair enough, but I believe it would make more sense for Canvas to send the SIS of the login the user used to log in. 

In our case, our continuing studies courses are hosted in a separate SIS. Some users have accounts in both SIS, and we merge their account so they have only one login. Their LTI launches sometimes send the continuing studies SIS ID, rather than the "primary", which breaks some of our tools that integrate with the main SIS. 

For custom tools, I can work around this by determining a canonical SIS ID, but external tools don't offer us this ability. 

Another potential workaround would be the ability to set a "primary" or preferred login that would be used for LTI launches.

**Comment by ccutrer** [comment]
While "current login pseudonym" intuitively seems to make more sense, it increases the chance of confusion on the tool side, since they'll see different IDs depending on how a user logged in. While your specific use case they may always use one or the other of the SIS IDs, that can't be guaranteed generally. With the current method, it's at least consistent what the tool will see, and generally tools care more about getting consistent IDs for a user, and not which ID it is they're receiving... unless the tool is subsequently linking the SIS ID up to another system, which it sounds like might be the case for you.

I'm pretty sure the logic when there is a conflict used to be to pick the one with a lower ID (created earlier), but that is a bit opaque since IDs aren't necessarily exposed easily in the UI, and you don't get a new ID if you destroy a login, and re-create it. So sorting by unique_id at least makes it easy to view a user and know which one will be sent.

All that said, I _have_ toyed with the idea of adding a position field to pseudonyms allowing you to choose a primary login like you can with communication channels. I just haven't done it yet because almost every case I've looked in to preferring a SIS pseudonym (and one in the local account for a multi-tenant/consortium situation) has been what they actually wanted anyway. It's relatively rare to use two disparate systems for SIS IDs in a single Canvas account, and if you have to do that, the recommendation is to use integration_id for the secondary system if possible.

**Comment by christopher-b** [comment]
> it increases the chance of confusion on the tool side, since they'll see different IDs depending on how a user logged in.

I don't necessarily see this as a bad thing. Our experience with multiple logins is that most people always use a single login; we merge accounts so our folks can see both sets of courses. We may be in the minority here.


> With the current method, it's at least consistent what the tool will see

This is true until an additional login is added to the user if that login is alphabetically first. 


>unless the tool is subsequently linking the SIS ID up to another system, which it sounds like might be the case for you.

This is the case for any tool that we pre-populate with data (ex: course evaluation) rather than tools that rely on LTI launch data. We have a good mix of both in use here. 


> if you have to do that, the recommendation is to use integration_id for the secondary system if possible.

I'm not sure I understand how this would work. Could you outline how we could use intergration_id to work around this issue?

Thanks for your attention to this.

**Comment by ccutrer** [comment]
Sure. The basic idea is that you use SIS ID for all logins created by your primary SIS, and integration ID for all logins created by the Continuing Studies SIS. Then when you configure your LTI tools, it will always send the SIS ID from the primary SIS, since that's the one with an SIS ID at all. If you still want to get the integration id (the SIS ID from the Continuing Studies SIS), you can use the Canvas.user.sisIntegrationId variable substitution instead/as well in your LTI tool.

A few caveats to this strategy:
 * while integration IDs can be set via SIS Import or API, you cannot set an integration ID _without_ a SIS ID in a regular SIS import. So if you're using SIS Imports, your Continuing Studies SIS would need to know the primary SIS ID to link them up. This may be a huge tripping point.
 * I haven't checked, but I suspect Canvas.user.sisIntegrationId will send the integration id from the primary pseudonym it finds, even if there isn't an integration id set on it, but there IS an integration ID on a different pseudonym for the user. This can definitely be improved.

**Comment by omarkhan** [comment]
Closing as this looks like a wontfix - happy to re-open if needed
