### ISSUE TITLE
Error on adding people to course

### ISSUE THREAD

**Issue by huangdengpan** [instructure/canvas-lms#1266]
When I add people to a course, it shows an error:
![image](https://user-images.githubusercontent.com/16663404/37981666-df6ca86a-3220-11e8-84dd-c59922ecd9b0.png)

Error reports as below:

The behavior of `attribute_changed?` inside of after callbacks will be changing in the next version of Rails. The new return value will reflect the behavior of calling the method after `save` returned (e.g. the opposite of what it returns now). To maintain the current behavior, use `saved_change_to_attribute?` instead.
![image](https://user-images.githubusercontent.com/16663404/37981737-10d7e022-3221-11e8-916e-8d95924a4219.png)

Thank you!

**Comment by huangdengpan** [comment]
@sdb1228 Do you know how to fix it ?

**Comment by omarkhan** [comment]
Hi @huangdengpan! I can't reproduce this issue locally. Please see [getting help](https://github.com/instructure/canvas-lms/wiki#getting-help) for support. Thanks!

**Comment by huangdengpan** [comment]
@omarkhan 
Ehh, I cannot visit google service from China.... 
I hope you can give me some advise.

When I tried to visite https://asjk.canvaslms.net/courses/1/enroll_users
it shows error 500.
The other pages work well.

Thank you!

**Comment by ccutrer** [comment]
@huangdengpan it sounds like you're running the master branch of Canvas (since that deprecation being an actual exception was just merged a few days ago), and also you likely have custom changes to Canvas (since all instances of this were already changed to the new behavior in the core canvas codebase). You should do exactly what the message says - change your code to call `saved_change_to_<attribute>?` instead of `<attribute>_changed?`. This is a deprecation from Rails 5.1, because the behavior changes in Rails 5.2.

**Comment by huangdengpan** [comment]
@ccutrer  Great! I am running the master branch of 20170327.
I am going to update rails or reinstall the sytem to be release branch.
Thank you so much!
