### ISSUE TITLE
How can i  auto login to the canvas from my website in php using api?

### ISSUE THREAD

**Issue by gautamchawla81** [instructure/canvas-lms#1284]
Hi Team,
Is there any possibility for auto login to canvas platform from my website?
Let me explain in brief.
In my website there will be a button "Login to canvas", When i hit that button then it should get the user loggedin details from my website and sent to canvas site and performs a auto login functionality. Is there any way i can implement this kind of functionality or similar ? My website and canvas website is on different domains. Provide some suggestions how this can be solved?

thank

**Comment by ccutrer** [comment]
The recommended way to do this would be to configure Canvas to use a third-party authentication system (https://community.canvaslms.com/docs/DOC-9870-4214406803) so that Canvas will automatically log in as the same user. You can either use a third-party to provide this authentication, or you could implement one of the SSO protocols that Canvas supports directly in your own application.

**Comment by thangnqpd03155** [comment]
yeah, I can do that, if you have a Admin Account.
