### ISSUE TITLE
My Canvas application suddenly stopped and showing index of /

### ISSUE THREAD

**Issue by gautamchawla81** [instructure/canvas-lms#1322]
Hello Team,

My application suddenly stopped working,
Please check here https://ec2-54-152-180-201.compute-1.amazonaws.com/
Its displaying files instead of login page.

Can you guys know what will be the problem?

Thanks

**Comment by amulgarg** [comment]
Have you installed passenger and configured it correctly?

**Comment by sdb1228** [comment]
I am going to close this given that the url provided is working.  Please reopen if the problem persists.

**Comment by Bellusterra** [comment]
I had the same issue with just the "index of /" showing and yes it turned out to be that passenger was not setup correctly.
I was able to resolve it following the instructions asked and answered by: [Márcio Quental](https://stackoverflow.com/users/6524825/m%c3%a1rcio-quental) on stack overflow

[Passenger using wrong ruby version](https://stackoverflow.com/questions/47931746/passenger-using-wrong-ruby-version/47941921#47941921?newreg=5278952f0bd14d09b13590d7a97ee03f)

Thank you Márcio and those above.

**Comment by gautamchawla81** [comment]
Hello Guys sorry for late reply. 
I just solved this by clearing drive cache. There was no space left so i cleared and it worked perfect.

I did so much research on this and found that its the problem of disc space. :)

**Comment by Sachin-Suresh** [comment]
@gautamchawla81 - Could you please tell me how you cleared drive space! Seems strange that this is the cause of the space issue.
This is my `passenger.config` file:

>  <IfModule mod_passenger.c>
> 
> >   PassengerRoot /usr/lib/ruby/vendor_ruby/phusion_passenger/locations.ini
> 
> >   PassengerDefaultRuby /usr/bin/passenger_free_ruby
> 
> >   PassengerDefaultUser example-user
> 
> > </IfModule

>
