### ISSUE TITLE
Quiz access code is password field so browsers try to save it

### ISSUE THREAD

**Issue by ucraida** [instructure/canvas-lms#1327]
### Summary:
The quiz 'access code' field is marked as password so browsers prompt to save it. 

### Steps to reproduce:

 1. Add access code to quiz
 2. Start quiz enter code

### Expected behavior:
 3. Browser does not ask to save password. 

### Actual behavior:
 3. Browser asks to save password. 

### Additional notes:
Current method for doing so is marking the field read-only until it is focused like so:

<input type="password" name="Password" autocomplete="off" readonly 
onfocus="this.removeAttribute('readonly');" >

https://stackoverflow.com/questions/41217019/how-to-prevent-a-browser-from-storing-password

**Comment by tierra** [comment]
Your Stack Overflow answer linked makes it sound like it's not possible to disable this functionality. One of those hacks to do it (that involve marking it as `readonly`) would make it non-accessible, so that's not an option either. The other hack involves not marking it as a password field, which breaks security features. So I'm really not seeing any option that could this.

**Comment by ucraida** [comment]
Thanks for the reply, didn't realize the accessibility issue on read-only. I agree there is no good solution right now.

**Comment by erizojuega** [comment]
hi i just want to ask about something if anyone knows to to hack a canvas quiz  because it's struggle to get some answers right if anyone  could help i while really appreciate that, thank you
