### ISSUE TITLE
Module Font Size is too small for student

### ISSUE THREAD

**Issue by pdgolfer** [instructure/canvas-lms#1338]
Hi

I have a visually impaired student and need to make the font size on the Module section larger.  I am not able to find a variable to change.  I need the font to be a minimum of 18pt in size.  Any suggestions?  Thank you in advance for your help.

**Comment by vimalloc** [comment]
Have you tried changing the zoom level on the browser itself?

**Comment by mdjasper** [comment]
Canvas account administrators can create custom themes, and upload custom css https://community.canvaslms.com/docs/DOC-10891-4214418311, but these apply to an entire account (institution level). The best option here is for the user to adjust their browser font size, or simply press Ctrl+ until the font is big enough on the current page. Here's a guide for chrome but it's basically the same in all browsers https://support.google.com/chrome/answer/96810?hl=en. I'm going to close this issue because we use GitHub issues for bug report, not general help, but good luck!

**Comment by mdjasper** [comment]
FYI, there are a couple other features that users can enable that help with other types of visual accessibility issues, like "high contest mode", if something like that would be useful in your specific case https://community.canvaslms.com/docs/DOC-10615-4212717415
