### ISSUE TITLE
Comment deletion responds with HTTP 422 CSRF(?) error

### ISSUE THREAD

**Issue by magneticflux-** [instructure/canvas-lms#1350]
### Summary:

I'm trying to delete all previous comments that match a certain pattern and then add a single comment (with an uploaded PDF of graded work) in an attempt to make some custom grading software idempotent. However, it seems like the only functioning API for comments is for adding them. Is there any way around this limitation? Is this method of deletion unsupported?

### Steps to reproduce:

 1. Make a comment programmatically
 2. Try to access/delete it through `https://www.example.com/submission_comments/:id`

### Expected behavior:

The comment is shown or deleted, depending on the verb used.

### Actual behavior:

HTTP 422 error, CSRF(?) related.

**Comment by SecurityInsanity** [comment]
If you notice there's no `/api/v1` in the beginning of this URL. That's because you're not hitting an actual API endpoint, but hitting just an endpoint within the app. All endpoints that aren't part of the API are protected from CSRF. 

Although I won't go into the details of _why_ CSRF protection is important. However in this case to keep using the same behavior you can get the CSRF token from the form on the page: `https://${host}/courses/${course_id}/gradebook/speed_grader?assignment_id=${assignment_id}` , and then send a POST to: `https://${host}/courses/${course_id}/assignments/${assignment_id}/submissions/${submission_id}` with a body like:

```
_method: PUT
authenticity_token: "token_i_got_from_the_first_pages_form_element"
submission[assignment_id]: `${assignment_id}`
submission[comment]: "my comment"
submission[draft_comment]: false
submission[group_comment]: 0
submission[id]: `${my_submission_id}`
```

This is probably not the best way, I'll let someone else comment on that as I haven't looked into the submission comment APIs, but that is a way of working with non-api endpoints from a pragmatic perspective in general.

**Comment by magneticflux-** [comment]
Thanks for the info. So it's best not to use this endpoint for an external application then?
I hope the API for submission comments is expanded soon, but I'll just have to restructure my application for now since having that many requests for every comment would get a bit ridiculous.
