### ISSUE TITLE
Misleading pagination for gradebook history days

### ISSUE THREAD

**Issue by sumnerwarren** [instructure/canvas-lms#1395]
### Summary:
The API for [gradebook history days](https://canvas.instructure.com/doc/api/gradebook_history.html#method.gradebook_history_api.days) is paginating results in a very misleading way. Currently, this API is (roughly) implemented by fetching the list of submissions for the provided course and then using that list to construct a map of dates to graders/assignments. The pagination is happening during the first portion: fetching the list of submissions. As a result, the constructed date map often lacks complete information for a given day, which means that a single day may be split across multiple pages of the response from this API.

This is problematic for two reasons:
1. Regardless of the `per_page` option's value, the number of pages is likely greater than the number of days with gradebook activity. For example, in one of our courses there are only 78 distinct days with gradebook activity, but 118 pages of responses from this API even with `per_page` set to the max of 50. This API currently requires more requests than necessary to receive the complete list of relevant days.
2. The list of graders and relevant assignments for a particular day might not be complete unless correctly combined with the other pages containing information for the same day. For example, in the same course a lot of grading took place on 2018-11-16. This day spans 11 pages in this API and contains gradebook history for 8 different graders, but many of the pages only report one or two of the relevant graders for this day. Only by combining the results from all 11 relevant pages can you determine that 8 graders were active that day.

I understand that consumers of the API should be prepared to deal with pagination, but this goes beyond the normal requirement of concatenating lists and makes it, I think, very easy to drop relevant information as a consumer.

I would argue that pagination does not make sense for this endpoint given that it's just returning a map. It seems the pagination is potentially making the load on this API (and the submissions database table) worse rather than better. However, if pagination must remain, I believe it should be applied to the number of included days instead of the number of underlying submissions relevant to those days. Or at the very least, the API documentation should mention this misleading behavior.

### Steps to reproduce:

 1. Create a course with one assignment, two students (A and B), and two teachers (C and D)
 2. Create a submission as each student
 3. Enter a grade for student A as teacher C
 4. Enter a new grade for student B as teacher D
 5. Call the days API with `per_page=1`
 6. Call the days API with `per_page=1` and `page=2`

### Expected behavior:
The API response includes a single date key with two graders (teachers C and D)

### Actual behavior:
The API response include a single date key with only teacher D in the graders list and the `Link` header indicates a second page of results exists. The second page only includes teacher C in the graders list for the same date returned in the first page of results.

**Comment by simonista** [comment]
Hi @jswarren, just wanted to say thanks for the detailed description of the issue and for including simple reproduction steps. It's really helpful to start a conversation with such a clear description!

It is true that most of the pagination throughout canvas is based solely on the number of results returned, which means that other factors like dates may be split across multiple pages. So I'm not sure this would be considered a bug, but I will make sure someone from our Gradebook team reads through this and thinks about it as well.

A few points I'd be interested to here your thoughts about:

1. You said "I would argue that pagination does not make sense for this endpoint given that it's just returning a map. It seems the pagination is potentially making the load on this API (and the submissions database table) worse rather than better." Can you expand on that? Generally the main purpose of pagination is to prevent loading an unbounded amount of data from the database, and keep response sizes (and times) reasonable. Course submission count can grow quite large, since submissions is the cross product of students and assignments, and so a course with 100 of each could easily have 100,000 submissions, which is a lot of data to move from postgres -> ruby, and a lot of data for ruby to transform into json. This can balloon our server process, and could also cause the request to hit the timeout limit of 60 seconds. I haven't studied it too closely, but an [initial read of the code](https://github.com/instructure/canvas-lms/blob/master/lib/api/v1/gradebook_history.rb#L129) seems to suggest that the pagination present prevents those issues. It is true that if you exhaust pagination, it is actually more total work for our servers because there's some duplicate overhead in authentication/authorization/etc, but that's fairly minimal, and we'd actually prefer more work but spread out over a number of server processes (and time), vs slightly less work all at once.

2. If you're looking for info about a specific date, it seems like maybe the [Details for a given date](https://canvas.instructure.com/doc/api/gradebook_history.html#method.gradebook_history_api.day_details) endpoint might be a better fit. You'd still have to exhaust pagination, but you'd know that after exhausting pagination you definitely had all (and only) the records for that date. If your looking for a date range, I'm wondering if the [grade change audit log](https://canvas.instructure.com/doc/api/grade_change_log.html#method.grade_change_audit_api.for_course) might also be worth looking at?  I'm sure your aware of both of these, but would like to better understand the use case you have.

3. Not super relevant to your argument, but in case it's helpful, the api per_page maximum is actually 100. (It's [default is 50 in the code](https://github.com/instructure/canvas-lms/blob/master/lib/api.rb#L287) but we've raised it to 100 in our production environments)

All that to say, I apologize for the confusion this has caused you, and the extra work that pagination adds to development (we feel it too, when we build our own front end code). At the very least, I think it would be totally reasonable to add some documentation to the endpoint that a single day may span multiple pages. But we will discuss it internally and see if we can come up with other ideas too.

**Comment by jswarren** [comment]
1. Yea, I was more thinking about the case of exhausting pagination and how that leads to potentially a ton of database queries. But you're right, spreading the load is better. I think what I meant by "pagination doesn't make sense..." is that, to me, the idea of a "page" doesn't really fit with the return type of this API since it is not a list. It's been a while since I've used the Canvas APIs and they have grown a lot since then, so it could be that returning a partial mapping is fairly common now, but it just seemed a bit strange to me. The weirdest thing is the date-splitting. I think this API would be more user-friendly if that could be avoided. I could be over-simplifying, but it seems unnecessary to pull every submission when all you're really building is a list of distinct `{ date, grader_id, assignment_id }` sets?

2. I am aware of both of these. The use case I was working on was basically auditing all grades given by a particular grader. I did end up using the date-specific endpoint to accomplish this, but I first needed discover the "active" dates for the grader. I think the grade change log is what I would ideally use for the current use case, however it is not returning any results for any courses in the sub-account in question. One of my colleagues said he discussed this with someone at Instructure and was told some of our "custom code" is causing that issue. I haven't had a chance to look into this yet (it seems unlikely since the only "custom code" we have is client-side JS overrides), but that is a separate issue that I'll need to sort out at some point.

3. That's good to know. Thanks for the info!

It is very possible there's not a better way to do this and that I'm just being optimistic/picky. If that's the case, I do agree that documentation could help prevent confusion for other API consumers. Thanks for the quick and detailed response!
