### ISSUE TITLE
6 packages are missing script

### ISSUE THREAD

**Issue by drew-royster** [instructure/canvas-lms#1397]
### Summary: 

Following the quickstart steps, I am having an issue on the Canvas dependencies section. 

`yarn install --pure-lockfile` ends saying `6 packages are missing script`

### Steps to reproduce:

 1. Follow setup until Canvas Dependencies Section
 2. bundle install
 3. yarn install --pure-lockfile

### Expected behavior:

No errors

### Actual behavior:

It returns

`6 packages are missing script  build:canvas: i18nliner-canvas, selinimum, @instructure/babel-preset-pretranslated-format-message, @instructure/canvas-supported-browsers, old-copy-of-react-14-that-is-just-here-so-if-analytics-is-checked-out-it-doesnt-change-yarn.lock, canvas_quizzes`

**Comment by claydiffrient** [comment]
@drew-royster Thanks for the report.  This message can safely be ignored.

Let me explain more of what's happening here.  As part of our front-end build step, we go through several of our internal packages (/packages/*) and attempt to run the `build:canvas` command against them.  Some of them require this step in order to be optimized for canvas, but others don't have this command because for various reasons, it isn't needed.
