### ISSUE TITLE
yarn version downgrade??

### ISSUE THREAD

**Issue by tloudon** [instructure/canvas-lms#1484]
Hi,

It looks like yarn was downgraded from 1.10.1 to 1.6 in https://github.com/instructure/canvas-lms/commit/ade362e5158e27019b69bd4d0be193fd3b91d2bd -- bump node to v10.

Was that intentional or was that a regression?

I'm trying to get a fresh version of the site up and running, but am running into issues w/ newer software than the Ubuntu 16.04 guide.  I got errors w/ yarn v1.16 about node-sass 4.7.2 which seem like they could be related to the node-gyp/node-tar exploit (I didn't dig into it too much).  I'm also not sure what this means "if we let node-sass upgrade to recent versions, it causes: SIS-3125" from the package.json -- I couldn't find any reference to it on the googs.  Is there a ticket on the node-sass issue that has us pinned to 4.7.2?  It would be awesome if you could just install everything w/ recent versions of bundler and yarn..

Thanks!

**Comment by claydiffrient** [comment]
I forget the exact reasoning for why I did that, however with the way semantic versioning works, anything in the 1.x.x range range of versions should be accepted as long as it is greater than 1.6.0.  I'm running 1.13.0 locally at the moment.

SIS-3125 is an internal ticket number.  It's an issue where upgrading node-sass causes flash messages to appear incorrectly.  The fix for now has been to just pin to 4.7.2 until a proper fix can be prioritized.

Hopefully that information helps.

**Comment by tloudon** [comment]
Thanks @claydiffrient!  Appreciate the quick response.  Cheers
