### ISSUE TITLE
"Production Start" Documentation Postgres Package Doesn't Exist

### ISSUE THREAD

**Issue by UniWrighte** [instructure/canvas-lms#1519]
### Steps to reproduce:

 1. Following the "Production Start" guide, install postgres on Ubuntu 18.04
 2. Use `sudo apt-get install postgresql-9.5`

### Expected behavior:
Install package for Postgres
### Actual behavior:
```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package postgresql-9.5 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'postgresql-9.5' has no installation candidate
```

**Comment by tierra** [comment]
The instructions do say it's written for Ubuntu 14.04 and 16.04 releases, and 16.04 is what uses `postgresql-9.5`. In any case, any newer version of PostgreSQL works too, so you can just adapt that for the version provided in your version of Ubuntu (which is `postgresql-10`). You'll also find that you need to use `ruby2.5` instead of the listed `ruby2.4`.

That said, it would be nice to see that document updated for use with Ubuntu 18.04. It's a wiki page, so feel free to make the appropriate changes if you're willing.
