### ISSUE TITLE
Cannot change SAML SP entity ID in case of domain change of production instance

### ISSUE THREAD

**Issue by Thyroxine** [instructure/canvas-lms#1813]
### Summary:

SAML Service Provider entity ID URL (`http://<domain>/saml2` on Authentication page and in the XML provided from this URL is created from domain in `config/domain.yml` on initial database population and cannot be changed in case of domain change by methods other than altering database manually and resetting Redis cache.

Also, even if the domain in database is correct and not changed, the URL is always shown with `http`, not `https` independently of SSL being enabled in Apache.

### Steps to reproduce:

 1. Install Canvas following [Production start](https://github.com/instructure/canvas-lms/wiki/Production-Start) Wiki page using `<old domain>` setting in `config/domain.yml`. 
 2. Change domain to `<new domain>` in `config/domain.yml` and Apache config.
 3. Restart `apache2` and `canvas_init` daemons/
 4. Go to Authentication page (`https://<new domain>/accounts/site_admin/authentication_providers` and try to add SAML identity provider. 
5. Go to `https://<your new domain>/saml2` and obtain XML response from it.

### Expected behavior:

1. (Preferred) Automatic change of domain in SAML identity provider from `http://<old domain>/saml2` to `https://<new domain>/saml2` on the Authentication page and in the XML by using setting in `config/domain.yml`.
or
2. A documented method to override URL stored in the database, e.g. by creating `config/saml.yml`.
3. URL should be with `https` scheme in both places.

### Actual behavior:

It shows `https://<old domain>/saml2` on the Authentication page and the same URL in `<EntityDescriptor entityID>` XML attribute in the response from URL `https://<new domain>/saml2`

![SAML1](https://user-images.githubusercontent.com/10007729/107582072-0be59480-6c0a-11eb-8c1a-fa6502ecd03d.PNG)
![SAML3](https://user-images.githubusercontent.com/10007729/107582391-77c7fd00-6c0a-11eb-99ff-fc11dd382c68.PNG)

I've tried to override entity ID by creating `config/saml.yml` from `config/saml.yml.example`
```
production:
  entity_id: "https://<new domain>/saml2"
  tech_contact_name: "John Smith"
  tech_contact_email: "superadmin@newdomain.com" 
```
with the following restart of `apache2` and `canvas_init` daemons, nothing changes except for `ContactPerson` field in the XML.

### Additional notes:
The problem was already asked on [Canvas Forum](https://community.canvaslms.com/t5/Question-Forum/How-to-change-Canvas-SAML-Entity-ID/td-p/413710) without solution.

I tried to manually edit `settings` column of `accounts` table of `canvas_production` PostgreSQL database by using JetBrains DataGrip for both rows with `id` 1 (Main Account) and 2 (Site Admin), and then restart `apache2` and `canvas_init` daemons. It helped for the URL on the Authentication page, but not for the XML.

![SAML4](https://user-images.githubusercontent.com/10007729/107582620-cb3a4b00-6c0a-11eb-9f2c-b3a76ce8fc33.PNG)

To change address in the XML I also had to reset Redis cache (shutdown `redis-server`, `apache2` and `canvas_init` daemons, move `/var/lib/redis/dump.rdb` to another location, restart the daemons). If I restore original `dump.rdb`, it shows `<old domain>` in the XML response again.

**Comment by ccutrer** [comment]
This is intentional.

First, there is no requirement that SAML entity IDs be retrievable documents, simply that they are unique and parseable as URIs. It's simply convenience to make the metadata document available at the Entity ID's location. And in fact, it could be a problem if the Entity ID suddenly changes just because an SP is available at a new location. To this end, Canvas persists the entity ID when it's first used. There are legacy reasons that we default to http not https. I'd prefer https as well, but with a proper redirect from http to https for usability reasons, and HSTS, it's not really a security issue.

Anyhow, a relatively recent change is that if you remove all SAML configurations, it will un-pin the Canvas entity id, and when you create a new one, it will re-generate with the current domain. At this time we feel forcing Rails console access (which you should be using instead of database access, and then you won't have caching issues) the few times the entity ID legitimately needs to be updated in place ends up causing fewer problems than complaints about broken authentication by accidentally changing the entity ID.
