### ISSUE TITLE
Can't upload files with canvas rce api

### ISSUE THREAD

**Issue by kenxt** [instructure/canvas-lms#1898]
### Summary:
We have a self hosted latest stable canvas and canvas rce api , which is connected to our s3 compatible object storage. When we upload a file with canvas rce api, we get an error : 400 Bad Request， but the file was already uploaded to s3 compatible object storage.

### Steps to reproduce:

 1. login in  our canvas
 2. create a page in a course
 3. upload a file with canvas rce api

### Expected behavior:
 upload to s3 storage and insert the filename with https link to canvas rce editor
### Actual behavior:
the file was already uploaded to s3 compatible object storage，get an error: 400  bad request.
### Additional notes:
the error url is :
https://canvas-domain/api/v1/files/2790612/create_success?include%5B%5D=preview_url&on_duplicate=rename&uuid=weddtreKGe86jEPXuln7lIwkH2GCVsqKa3JksLlmx?bucket=331a60d07b0a4ac5b121dba66bf2b863-file&key=account_1%2Fattachments%2F2790994%2F%25E5%25A5%25BD%25E5%25A4%25A7%25E5%25AD%25A6%25E5%259C%25A8%25E7%25BA%25BF%25E9%2580AF%25BE%25E5%25A56.xlsx&etag=%2457cbcaf232aa20ca1f48596feb5c9cba%22

We found two question marks in the url, the second should be & before the key: bucket.

We could not find how to correct the url.

**Comment by GTMtremolo** [comment]
Hi, have you fixed that yet

**Comment by kenxt** [comment]
> Hi, have you fixed that yet

I couldn't find how to fix it

**Comment by ror-prem** [comment]
I found this helpful
https://github.com/instructure/canvas-rce-api/issues/12

**Comment by Thyroxine** [comment]
Which one S3 compatible storage are you using?

**Comment by Thyroxine** [comment]
Hello everyone, the problem was finally resolved in the MinIO version [2022-07-13](https://github.com/minio/minio/releases/tag/RELEASE.2022-07-13T23-29-44Z)!

It was fixed in this [Pull request](https://github.com/minio/minio/pull/15280).

I've succesully connected Canvas with it (see my config above) and RCE file upload is now working!
We can now use our on-premise S3!

For MinIO Deployment I used [Docker compose](https://docs.min.io/docs/deploy-minio-on-docker-compose.html) and [NGINX reverse proxy](https://docs.min.io/docs/setup-nginx-proxy-with-minio.html) with Let's Encrypt SSL Certs.

**Comment by nosadcoder** [comment]
I can help you!

**Comment by huangdengpan** [comment]
它这个网址里有2个问号导致的。它也不是minio的问题。
