### ISSUE TITLE
Phishing risk via iframes in submissions

### ISSUE THREAD

**Issue by garlic-os** [instructure/canvas-lms#1923]
### Summary:
Students can use `<iframe>`s to embed websites into their submissions. These sites can be malicious, and will appear on the grader's end. The things `<iframe>`s offer obviously have lots of legitimate uses in student submissions, but they give students too much power over how their submission appears to the teacher.

While it may not be possible for a student's submission to run JavaScript directly on the Canvas page or otherwise take it over, student submissions fill almost the entire screen while on the grading page, and the website on the other end can appear however it wants. Among many things, this ability can be abused to fool an unsuspecting grader into entering their Canvas (or school-wide) login credentials. A submission can be crafted to appear as if Canvas needs the grader to log in again before continuing, only to send their credentials to a server operated by a bad actor. Below I've included a proof-of-concept of a password-stealing fake login page.

### Steps to reproduce:

 1. As a student, click the `</>` button in the bottom right corner of a submission window for an assignment, discussion reply, etc.
 2. Add the HTML code for an iframe, like `<iframe src="https://fake-school-login-page.com/"></iframe>`.
 3. Submit.
 3.5. (Wait for the class's teacher/grader to see your submission.)

### Expected behavior:
Students can not embed arbitrary websites into their submissions.

### Actual behavior:
Students can embed arbitrary websites into their submissions, which is a security risk.

### Additional notes:
Proof of concept: a submission that presents the grader with a fake login page before proceeding to the student's submission after they submit the form
https://www.youtube.com/watch?v=H8zpzuE8vYc

**Comment by the-garlic-os** [comment]
Any progress? Proof of concept still works in the latest version of Canvas.

**Comment by xandroxygen** [comment]
Thanks for opening this issue, sorry it went so long without a response. You are right in that allowing students to embed arbitrary content can lead to malicious scenarios and should be limited - but the use of iframes and more broadly, embedding content, is central to Canvas's LTI features. Even widely-used LTI tools like YouTube embed an iframe inside submission and other content. So blocking iframes wholesale won't be something that we limit or pursue, and we have turned down bug reports for this in the past.

But! This is a pretty well-known problem across the web, which has lead to the rise of the [Content Security Policy (CSP)](https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP) header. Canvas supports this header at a school level by enabling the "Content Security Policy" Account-level feature flag, then configuring the header in the Acccount Settings -> Security tab. By default, this header will include all domains for installed LTI tools, but nothing else. That way, with this header enabled, students can embed iframes all they want but arbitrary domains like `https://fake-school-login-page.com` will be blocked from rendering by the browser. 

Does this help/can I answer any further questions? For now, I'm going to have this marked as closed since there is a solution and there won't be any further work done on this.
