### ISSUE TITLE
Script Bundle install failed

### ISSUE THREAD

**Issue by namila007** [instructure/canvas-lms#1940]
### Summary:
Im trying to build canvas "release/2021-06-23.28" on  docker (installed in windows) using a ubuntu 18.04 container.(im using docker in docker binding windows docker.sock to container docker.sock) on here I gave the `./script/docker_Dev_setup.sh` to build . im getting the following error on "build_assets" step, 

```
> Building assets...
> Bundle install...
OCI runtime exec failed: exec failed: container_linux.go:349: starting container process caused "exec: \"./script/install_assets.sh\": stat ./script/install_assets.sh: no such file or directory": unknown 
```
 so I did the manual docker part without the script mentioned in here [docker getting started](https://github.com/instructure/canvas-lms/blob/master/doc/docker/developing_with_docker.md#getting-started). in here I was abe to run `docker-compose build` without error and when I execute `docker-compose run --rm web ./script/install_assets.sh` i got the same error
```
:~/canvas$ docker-compose run --rm web ./script/install_assets.sh
Creating canvas_web_run ... done                                                                                                         
Error response from daemon: OCI runtime create failed: container_linux.go:349: starting container process caused "exec: \"./script/install_assets.sh\": stat ./script/install_assets.sh: no such file or directory": unknown
```
how to fix this issue?

### Steps to reproduce:

 1. use ubuntu 18.04 image and run the bash on docker(installed in windows) with `-v "//var/run/docker.sock:/var/run/docker.sock"` args
 2. create a user, install git, docker,docker-compose and give permission to docker.sock, docker-compose and other relevant setups
 3. run docker setup script or follow the steps in here [docker getting started](https://github.com/instructure/canvas-lms/blob/master/doc/docker/developing_with_docker.md#getting-started)

### Expected behaviour:

above error

**Comment by jbutte** [comment]
@namila007 we've seen this issue before. The most common reason has been because you are missing that file in your local code. Can you verify you have `./script/install_assets.sh` in your local repo?

The second most common I've seen is a dirty old volume. So if you have that file locally try to cleanup your docker volumes.

**Comment by jbutte** [comment]
@deisner Copying of the script/ directory should be unnecessary with the volumes we are using. The docker_dev_setup script will copy over the docker-compose.override.yml which contains the volumes, specifically the first one `.:/usr/src/app` which will copy over your host directory to the docker container.  If you are not using our docker-compose.override.yml that could also result in this error. 

I do recommend using the mutagen setup though, it is the new way forward since boot2docker is deprecated.

**Comment by sinorrman** [comment]
Thanks for your steps @deisner!

As a side note, someone else might also run into issues building the mutagen containers with the following errors:
`[...] unable to connect to beta: unable to connect to endpoint: unable to dial agent endpoint: unable to create agent command: unable to probe container: container probing failed under POSIX hypothesis (exit status 1) and Windows hypothesis (exit status 1)`

Per [this answer](https://github.com/mutagen-io/mutagen/issues/300#issuecomment-952396655), it's due to Mutagen's lack of support for Compose V2. So until the Mutagen team has fixed it, make sure to run:
`docker-compose disable-v2`
before running the setup script.

**Comment by jbutte** [comment]
@namila007 can you confirm whether or not you are using our docker-compose.override.yml.example? Also if you've had a chance to try using the mutagen setup as @deisner suggested, did that work for you?

**Comment by namila007** [comment]
@jbutte sorry I deleted everything and tried it on ubuntu :D
