### ISSUE TITLE
Canvas Commons adding browser compatibility

### ISSUE THREAD

**Issue by amg-web** [instructure/canvas-lms#2062]
Canvas Commons adding workflow fail with chromium based browsers

At last step after we connect to with API id and key we get login window instead of success notification.

it's possible to open Commons site and navigate it but it's not actually integrated, and button does not appear on the sidebar.
the only working option is Firefox browser.

![Screenshot from 2022-06-08 15-50-11](https://user-images.githubusercontent.com/22151881/173188761-f74c9139-a8cf-4d3c-b14c-e28540b2f174.png)

**Comment by Ardena** [comment]
If you're doing this on a local installation, it's likely because the cookies are not secure, so Chromium based browsers are not sending them.  You can try setting up https to serve secure cookies and that should resolve this.  We've been working around it a bit for local development by using Firefox, but that may become more problematic long term.

**Comment by amg-web** [comment]
@Ardena 
I do it on self hosted installation on a remote server, using https and FQDN
