### ISSUE TITLE
Media file is processing. Please try again later.

### ISSUE THREAD

**Issue by fchienvuhoang** [instructure/canvas-lms#2196]
### Summary:
Cannot insert video to rce editor
### Steps to reproduce:

 1. Go to Account -> files -> upload -> choose a .mp4 file
 2. Go to Courses -> choose any course -> pages -> new page -> from editor -> insert media -> user media -> select all file users
 3. Click to my files to show all media file

### Expected behavior:
 Inserted a .mp4 file to editor

### Actual behavior:
Media file is process
<img width="923" alt="Screenshot 2023-05-01 at 15 25 55" src="https://user-images.githubusercontent.com/4451749/235429194-6540e052-cea8-45be-803c-cf9a92e6fdeb.png">
ing. Please try again later.

**Comment by Ardena** [comment]
Hello,

Canvas requires a media plugin (like Canvas's Studio or Kaltura) to be able to process video and audio files.

**Comment by virgo47** [comment]
Do I understand it right that self-hosted Canvas LMS installation (web+worker+RCE API) doesn't process uploaded media and can't embed it to Pages, not even as a link (because drag-n-drop doesn't work in this state)? Since when does this work this way? We have some older installation (~2 years), Kaltura is disabled there, but videos work.
