### ISSUE TITLE
course catalog or search function

### ISSUE THREAD

**Issue by cvong** [instructure/canvas-lms#330]
Hi,

Is there any course catalog or search function in the Canvas LMS? Thanks.

Chi-Hou

**Comment by claydiffrient** [comment]
@cvong Sorry for not responding to this sooner.  I'm sure you've probably figured this out or moved on by now.  We don't have a course catalog built into Canvas for users to find courses to enroll in.  We do however provide administrators the option to search for courses on the account level.

**Comment by jenseng** [comment]
@cvong @claydiffrient that's not entirely true, we actually added a simple course catalog feature a couple months ago ... see this commit for more information: https://github.com/instructure/canvas-lms/commit/2f917108

there's a feature flag called "Course Catalog" on the root account. once enabled, any courses you set as listed in the course index will appear in a public course catalog for your institution

**Comment by claydiffrient** [comment]
Thanks @jenseng for correcting my mistake.  I completely overlooked that before responding!

**Comment by lukest** [comment]
@jenseng does this feature include functionality that will permit and management student enrollment prior to course launch?

**Comment by jenseng** [comment]
@lukest yes...

#### To let users self-enroll in the course:

On the course settings page, under "more options", you'll want to enable the following:

* [x] Let students self-enroll by sharing with them a secret URL
* [x] Add a "Join this Course" link to the course home page

Once set, students will see a "Join this Course" button for the course within the catalog.

Additionally, you probably should also set course start/end dates and check this setting:

* [x] Users can only participate in the course between these dates

Otherwise students might be able to see course content before it is ready

#### For general management of enrollments:

You don't need to do anything special for this; since it's still a course like any other, administrators can manually create, update and remove enrollments in courses listed on the catalog.

**Comment by lukest** [comment]
Thanks @jenseng -- much appreciated!
