### ISSUE TITLE
Failed to build gem native extension

### ISSUE THREAD

**Issue by bostonhao** [instructure/canvas-lms#462]
I install Canvas following Production Start in ubuntu 12.0.4
when I run the command as below
sysadmin@appserver:/var/canvas$ bundle install --path vendor/bundle --without=sqlite

there is an error:Failed to build gem native extension

Using acts_as_list (0.0.1) from source at gems/acts_as_list
Installing addressable (2.3.5)
Using adheres_to_policy (0.0.1) from source at gems/adheres_to_policy

Gem::Installer::ExtensionBuildError: ERROR: Failed to build gem native extension.

        /usr/local/bin/ruby extconf.rb

Gem files will remain installed in 

/home/ubuntu/canvas/vendor/bundle/ruby/1.9.1/gems/nokogiri-1.5.6 for inspection.
Results logged to /home/ubuntu/canvas/vendor/bundle/ruby/1.9.1/gems/nokogiri-

1.5.6/ext/nokogiri/gem_make.out
An error occurred while installing nokogiri (1.5.6), and Bundler cannot
continue.
Make sure that `gem install nokogiri -v '1.5.6'` succeeds before bundling.
ubuntu@ip-10-254-47-82:~/canvas$

I do not know what's wrong, could anyone help me on this?

Thank you so much in advance

Heping

**Comment by simonista** [comment]
Hey @bostonhao, I'm so sorry no one ever responded to your issue here.  I'm assuming you've gotten it resolved in the intervening two years, but feel free to reach out again if you're still having issues.  You might try our email list, it can often be more helpful for issues like this, it's here: https://groups.google.com/forum/#!forum/canvas-lms-users
