### ISSUE TITLE
Flags for who can create new courses do not invalidate "Manually-Created Courses" account cache

### ISSUE THREAD

**Issue by jasonm** [instructure/canvas-lms#484]
When I update the JS/CSS overrides for an account (`Account.find(id).settings[:global_javascript]` and `Account.find(id).settings[:global_stylesheet]`) this doesn't take effect for all users.

I am using Redis to cache, and it appears that the value is cached:

```
>> Account.site_admin.reload
=> #<Account id: 2, name: "Site Admin", ...,  settings: {..., :global_javascript=>"correct-new-value", :global_stylesheet=>"correct-new-value", ...}, ... >
>> Account.find_cached(2)
=> #<Account id: 2, name: "Site Admin", ...,  settings: {..., :global_javascript=>"old-obsolete-value", :global_stylesheet=>"old-obsolete-value", ...}, ... >
```

Running `redis-cli get _account_lookup2/2` returns a repr of the Account which indicates the old value for these settings.

I manually call `Account.invalidate_cache(2)`, and then the cached value works.  I'm not very familiar with the Canvas codebase, but should the cache get invalidated by the Account in an `after_save`, or perhaps by the controller which updates it?

**Comment by simonista** [comment]
Hey Guys, sorry for the slow response on this issue.

I can't reproduce the global css/js caching issue, but the "create a new course" button issue I can reproduce.  It is actually not related to the account lookup cache, but to the permission cache.  The permissions cache for accounts uses the user and account to create a cache key, but because the permission flag is saved on the root account, but looked up on the "manually created courses" account, when the flag changes, neither the user or sub-account changes, so the cache key is not invalidated.  Luckily we have a TTL of 5 minutes on that cache so it fixes itself in a short period of time.  I've been trying to think of a nice way to fix this problem, but so far I haven't come up with anything except just manually touching the sub-account when the flag on the root account changes.  I'm going to keep thinking about it though.
