### ISSUE TITLE
Use foreman to manage processes during development?

### ISSUE THREAD

**Issue by djcp** [instructure/canvas-lms#508]
Is there any reason not to use foreman to spin up the rails server and delayed_job worker? This'd make running in development a tiny bit easier.

```
# Procfile.dev
web: bundle exec rails server
worker: bundle exec script/delayed_job run
```

```bash
cd canvas-lms && foreman start -f Procfile.dev
# magic happens
```

Happy to submit a PR with doc fixes and one additional minor gemfile dependency.

**Comment by claydiffrient** [comment]
@djcp The reason we choose not to do this is because of the various development servers that are in use.  For instance, I use http://pow.cx/ rather than the rails server.  If you would like to accomplish this for yourself you can add the `Procfile.dev` as well as the gem into `Gemfile.d/`.  Just make sure those things are excluded from your git repository by placing them into `.git/info/excluded`.  I'm going to go ahead and close the issue.  I hope this information helps!
