### ISSUE TITLE
Javascript error on Navigation based LTI tool pages

### ISSUE THREAD

**Issue by redconfetti** [instructure/canvas-lms#525]
I'm running the latest 'master' branch version of Canvas locally on my machine. I've refreshed this branch, ran npm and bundle install, and recompiled assets. I'm receiving a 'Uncaught TypeError: Illegal invocation' over and over on an LTI tool that I'm developing.

Its referencing the error as originating from line 95 of tool_inline.js

https://github.com/instructure/canvas-lms/blob/3596811/public/javascripts/tool_inline.js#L95

This seems to be related to the 'tool_content_wrapper' element that now wraps the iframe for LTI tools.

This isn't causing me any specific issues, however I'm just wanting to point this out to your development team as an FYI. The error isn't occurring on other pages.

**Comment by simonista** [comment]
Hey @redconfetti, so let me make sure I'm understanding this correctly, you are using postMessage for some unrelated thing, but we are catching the message, and since it's not JSON, the parsing fails and we throw an error. Is that right?  I'll have to think about the best way to handle this.  At a glance, it seems fine to not log an error in that case, but I'll run it past a couple other people.

Is this actually causing behavioral problems for you, or is it just annoying?

**Comment by redconfetti** [comment]
Hey @simonista, we updated our code to create a JSON string message to match the convention you set for your listener method. Your receiver ignores our messages, but our receiver function/method does receive and performs the requested action.

So we dealt with it as needed.

**Comment by simonista** [comment]
Ahh, so I had it flipped.  Sounds good, thanks!

**Comment by simonista** [comment]
Oh no, you mean ignored as in it checks the "subject" and then ignores it.  I get it :)

**Comment by redconfetti** [comment]
Yes. We updated our [messages](https://github.com/ets-berkeley-edu/calcentral/blob/9931338f/app/assets/javascripts/angular/services/utilService.js#L114), and our [listener](https://github.com/ets-berkeley-edu/calcentral/blob/9931338f/public/canvas/canvas-customization.js#L340) method to parse the JSON and check for a matching subject.
