### ISSUE TITLE
LTI resizing when content change

### ISSUE THREAD

**Issue by jorgevbo** [instructure/canvas-lms#541]
I was using https://github.com/davidjbradshaw/iframe-resizer before tool_inline.js changes.
Implementing lti.frameResize message, I have problems to detected resize when child iframe change content height, for example, when I use Tabs or paginated contents with JS and JQuery

**Comment by simonista** [comment]
Hey @jorgevbo, can you explain a little more what you are trying to do? If I'm understanding correctly, you're talking about the changes to tool_inline.js described here: 834aba7d2e412daefb47771ebe294426366ad36f ?  And you're struggling to send the message with the correct values dynamically based on content inside the frame?

**Comment by brainheart** [comment]
Has this code made it to the hosted canvas sites? I can't get the lti.frameResize to work and I think, poking through the minified js, that it isn't even there.

**Comment by claydiffrient** [comment]
@brainheart Yes the code has made it into hosted Canvas sites.  It was released as part of the 2014-10-18 release (https://github.com/instructure/canvas-lms/releases/tag/release%2F2014-10-18.01).  I can imagine that it'd be hard to find in the minified js.  You'll only see the `tool_inline.js` bundle on pages that result from an LTI launch.  If you need more information about that I'll try and connect you with some LTI experts around here.

**Comment by brainheart** [comment]
Ah, I think I see my problem. I have an LTI that uses the editor extension to insert an iframe into a page. Since that iframe is just a regular old iframe pointing to a regular old url, when a user views that page no LTI launch is triggered and so there's no tool_inline.js bundle loaded. Any chance that this or a similar mechanism could be extended to allow ordinary iframes to resize themselves? Or will we have to code this ourselves in the global js file? (we've been avoiding that).

**Comment by claydiffrient** [comment]
@brainheart I'll ping people from the appropriate teams and see what they think.

cc: @wbhumphrey @miquella

**Comment by brainheart** [comment]
Thank you @claydiffrient ! Much appreciated.

**Comment by wbhumphrey** [comment]
We are adding support to allow embedding iframed lti launches via content-item (http://www.imsglobal.org/lti/#cim1.0).  So instead of just linking to your content you could LTI launch to your content.  

That being said, I am not sure if the resizing stuff will work within the RCE though without further work trying to support that.  This may be an appropriate case for global js.

**Comment by brainheart** [comment]
Thanks, @wbhumphrey, global js is doing the trick for now (using the iframe-resizer library @jorgevbo mentioned above). The ability to have iframe resize is so generally useful that I wonder if you guys shouldn't consider making this library included by default (then all "tool providers" or even non LTI iframe content providers have to do is include the client side library).
