### ISSUE TITLE
Missing dependencies in package.json (stable branch)

### ISSUE THREAD

**Issue by kjellm** [instructure/canvas-lms#565]
Hi

I needed to add the following to `package.json` to stop `rake canvas:compile_assets` from failing due to missing dependencies:

    "handlebars": "~1",
    "ember-template-compiler": "~1.8",
    "i18nliner-handlebars": "~0.1",
    "minimist": "~1.1"

**Comment by jenseng** [comment]
those shouldn't be needed in the main package.json, as they are defined in [this file](https://github.com/instructure/canvas-lms/blob/master/gems/canvas_i18nliner/package.json) ... when you `npm install` or `npm update` from the root, [these lines](https://github.com/instructure/canvas-lms/blob/7420e67f/package.json#L41-L42) in the main package.json should ensure those dependencies are correct

which versions of `node` and `npm` are you running? also, what happens if you run `script/gem_npm install` on its own?

**Comment by kjellm** [comment]
I am building a Docker image based on the [Production Start](https://github.com/instructure/canvas-lms/wiki/Production-Start) wiki article. The [Dockerfile](https://github.com/matematikk-mooc/mmooc-docker-canvas/blob/master/Dockerfile) I use to build the image should be pretty close to an executable version of the Production Start document.

node is version 0.10.33, and npm is version 1.4.28

> what happens if you run script/gem_npm install on its own?

Will investigate that tomorrow.

**Comment by kjellm** [comment]
Figured out the problem. It was caused by running `npm install` as root. This has not been a problem on earlier releases for some reason.  Solution was to add `unsafe-perm = true` to `.npmrc`. Thank you for your time and help!
