### ISSUE TITLE
Permissions - how to restrict or allow access?

### ISSUE THREAD

**Issue by GildedHonour** [instructure/canvas-lms#582]
I've been trying to understand how the permission system works and couldn't. What I want to do is to restrict or allow access for a user (student) to the courses depending on whether or not they pay. How can I do that?

**Comment by simonista** [comment]
Hey @GildedHonour, how are you keeping track of whether or not they have paid?

**Comment by GildedHonour** [comment]
For now I don't, isn't there a built-in solution for that (or not exactly for that) in canvas? If not, I can add a bool field "is_paid_for_this_month".

**Comment by simonista** [comment]
Hmm, I'm not sure exactly what the best solution would be, but I think what some people do in this case is keep track of tuition status externally and then set the enrollment state to either active or deleted based on whether payment has been received.  This could be done with either the api or a SIS batch update (see https://canvas.instructure.com/doc/api/file.sis_csv.html).  The permission system in canvas is fairly granular, so you could get in and edit several of the set_policy blocks on different objects to check for your new boolean field, but that feels like a lot of work to me.

**Comment by GildedHonour** [comment]
Thanks. How can I edit them exactly?

**Comment by simonista** [comment]
So for example, see https://github.com/instructure/canvas-lms/blob/stable/app/models/course.rb#L1017.  You'd have to look through the permissions you want to take away (probably :read and maybe others) and then add conditions in the `given` blocks that would otherwise return true for students, to return false if they haven't paid.  That would block access to the course itself, and it should block access to most course content (most content should ensure that users can :read the course as part of their own permission checks).  The downside of changing core files like this is that it makes updating more difficult when the stable branch is updated every 3 weeks.  The course permissions already there tie into the enrollment state, which is why I suggested that direction.

**Comment by GildedHonour** [comment]
What I need is to simulate this http://d.pr/i/1gbll (set up via web interface - UI) **programmatically (dynamically)** depending on whether an user has paid or not.

You see, all the courses in Real Number System get available for a student once they "pass" Introduction, and Introduction is a quiz but technically paying via paypal. Once they pay via paypal, they get a code, they enter it in that quiz (Introduction) and that means they pass it, they gain access to  Real Number System. But that's a temporary solution . 

How does the permission system work there? I've tried to find it out by going through the code and couldn't.

**Comment by simonista** [comment]
Any reason to just not enroll the user in the course until they've paid?  I'm not sure how else to direct you; messing with permissions code directly is digging into the core of some complicated models, it's going to be messy.

**Comment by GildedHonour** [comment]
Do you have an idea where it is in the code - how to enroll/not enroll them?

**Comment by GildedHonour** [comment]
And the student can enroll in the courses themselves, right? So I can't control that.
