### ISSUE TITLE
 Files uploaded to quizzes cannot be viewed or downloaded

### ISSUE THREAD

**Issue by va7map** [instructure/canvas-lms#611]
This seems to affect Canvas installations that are using a local file system to store file uploads.

Steps to reproduce:

1. Create a quiz with a File Upload question
2. Complete the quiz by uploading a file
3. View the submission, and click on the link for the file you just uploaded

Instead of displaying/download the file, it gives a Page Not Found error that's caused by an underlying Routing Error.

When the attachment backend is a local file system, the link URL is given by `Attachment#local_storage_path`. It uses the attachment's context to create a path that looks like this:

    quizzes/quiz_submissions/:quiz_id/files/:attachment_id/download?verifier=:verifier

I don't think this is a valid route in Canvas, so this would explain the Routing Error. Perhaps the routes for quiz file uploads are somehow missing?

**Comment by patchin** [comment]
I found out that a path without the leading "quizzes/" works:

    quiz_submissions/:quiz_id/files/:attachment_id/download?verifier=:verifier

The problem starts with the code that generates the path (attachment.rb):

    def local_storage_path
      "#{HostUrl.context_host(context)}/#{context_type.underscore.pluralize}/#{context_id}/files/#{id}/download?verifier=#{uuid}"
    end

context_type initially starts out as "Quizzes::QuizSubmission" but is transformed into "quizzes/quiz_submissions" through the following code:

    #{context_type.underscore.pluralize}

Why is the value of context_type "Quizzes::QuizSubmission"? It's because of this line in attachment.rb:

    override_polymorphic_types context_type: {'QuizStatistics' => 'Quizzes::QuizStatistics',
                                            'QuizSubmission' => 'Quizzes::QuizSubmission'}

I'm not an expert in the codebase so I don't understand all the ramifications of the context_type property. So I don't know what would break by removing the "QuizSubmission" entry in the override_polymorphic_types call. I took a look at override_polymorphic_types and the source code sent shivers down my spine!

**Comment by va7map** [comment]
As far as I can tell, the `QuizSubmission` context became `Quizzes::QuizSubmission` within an Attachment about a year ago: https://github.com/instructure/canvas-lms/commit/d85c1006b498d10cf79d331cd1bfa5a871fe7b98. It was meant to fix the file download link *(CNVS-11986 and CNVS-11672 — I don't have access to those issues, so I don't know how it was broken before)*, but it appears to cause `Attachment#local_storage_path` to generate an invalid path.

I wonder if @devrieda could offer some insight into this.

**Comment by simonista** [comment]
Hey @va7map and @patchin, like you guys have theorized (and as cody mentioned on the mailing list), the override_polymorphic_types stuff was necessary so that when we namespaced the quizzes classes, we didn't have to change the value in the database for ever row that referenced a polymorphic table related to quizzes.  So we need to leave that as is.

A couple ways off the top of my head I can think of to fix this is either manually catching that case in the local_storage_path method and transforming back to just quiz_submissions or adding a route to handle the url with quizzes/quiz_submissions that points to the same place.

**Comment by va7map** [comment]
The [routes for quiz submissions concerning files](https://github.com/instructure/canvas-lms/blob/c319dd3662558676d08a6c5ed10ae3aba451d759/config/routes.rb#L753-L755) seemed to be written before QuizSubmission was namespaced. I wonder if we can add an entry like this:

```ruby
scope '/quizzes' do
  resources :quiz_submissions do
    concerns :files
  end
end
```

That'll create an extra set of routes prefixed with `/quizzes` that points to the same place. And maybe we can even replace the existing entry with this one if all existing usage can tolerate the prefix.

**Comment by va7map** [comment]
@simonista I should have mentioned this at the Hack Night. Do you think my suggestion above is a reasonable fix?

**Comment by samuels410** [comment]
@va7map Its worked .
Thank you :clap:

**Comment by va7map** [comment]
This issue can be closed because the fix was included in the [2016-04-23 release](https://github.com/instructure/canvas-lms/releases/tag/release%2F2016-04-23.01). Thanks everyone!
