### ISSUE TITLE
Canvas LTI Import by URL doesn't work

### ISSUE THREAD

**Issue by Syerram** [instructure/canvas-lms#630]
Few of our users are unable to open up our tools due to LTI integration issue. Here is the [XML configuration](https://s3.amazonaws.com/kipinhall-main/static/assets/kipin-canvas-lti-attendance.xml). Canvas sends "fake" as a consumer key instead of the consumer key provided by us. 

Could be a duplicate of [this](https://github.com/instructure/canvas-lms/issues/297)

This is preventing few institutions from using the app. Can you help us resolving this?

**Comment by claydiffrient** [comment]
@Syerram I'm sorry this issue is happening for you.  I'm also sorry we haven't been more responsive to this.  I've reached out to @wbhumphrey from our platform team.  He may have more information on this for you.

**Comment by wbhumphrey** [comment]
Canvas doesn't get a key or secret from the provided configuration. If users are copying or importing course data that has LTI tools in it, they will have to reconfigure the key/secret each time they import the tool. This is necessary because placing the key and secret in a CC file would compromise the security of the tool.
