### ISSUE TITLE
Module item titles are too aggressively truncated

### ISSUE THREAD

**Issue by ybakos** [instructure/canvas-lms#657]
When a browser window width is below a particular threshold, the module item titles are truncated with an ellipsis. While desirable to accommodate narrow windows, this seems to happen too soon. I have attached two screenshots below.

While I realize there is additional data such as # of points, etc to include in the element, it still seems truncation could be more forgiving. Sometimes there is important information at the end of a title, such as the minutes and seconds of a video.

Thanks for all things Canvas!

**Full width, no truncation. (Good)**
<img width="1471" alt="screen shot 2015-07-07 at 11 18 24 am" src="https://cloud.githubusercontent.com/assets/5502/8552495/b19117be-249a-11e5-8243-d97e6242640b.png">

**Less than full width, aggressive truncation. (Bad)**
<img width="1068" alt="screen shot 2015-07-07 at 11 18 38 am" src="https://cloud.githubusercontent.com/assets/5502/8552496/b1b5285c-249a-11e5-8b2d-9a1f100249a3.png">

**Comment by simonista** [comment]
Hey @ybakos, thanks for the report.  Unfortunately, this is kind of a complicated situation, since there is a bunch of metadata that COULD show up in that blank white space (here's an example of what it might look like: https://www.dropbox.com/s/1r1zp15k91k0km8/Screenshot%202015-07-29%2015.43.52.png?dl=0).  So it's actually truncating at a fairly reasonable place when all that metadata appears, it just is a bummer when it's not there.  I don't think we have any plans to try to make this smarter in the near-term though.

Hope that all makes sense, and thanks for the report.
