### ISSUE TITLE
Error at the step of Test database configuration

### ISSUE THREAD

**Issue by ehongyu** [instructure/canvas-lms#665]
I am following the Quick Start tutorial at https://github.com/instructure/canvas-lms/wiki/Quick-Start, and at the step of Test database configuration I ran into the following error

```
$ bundle exec rspec spec/models/assignment_spec.rb
Bullet Instructure not enabled
/home/vagrant/.gems/bundler/gems/rails-b344986bc3d9/activerecord/lib/active_record/connection_adapters/postgresql_adapter.rb:1222:in `initialize': fe_sendauth: no password supplied (PG::ConnectionBad)
	from /home/vagrant/.gems/bundler/gems/rails-b344986bc3d9/activerecord/lib/active_record/connection_adapters/postgresql_adapter.rb:1222:in `new'
	from /home/vagrant/.gems/bundler/gems/rails-b344986bc3d9/activerecord/lib/active_record/connection_adapters/postgresql_adapter.rb:1222:in `connect'
....
```

My environment is Ubuntu 14.04.2 LTS running in a vagrant VM under Mac OS.

**Comment by rivernate** [comment]
It sounds like your postgres installation is configured to require a password. If your running postgres on the same box as your canvas installation this stackoverflow question may help: http://stackoverflow.com/questions/17996957/fe-sendauth-no-password-supplied.  
Otherwise if you are running it on a separate box you will need to do some additional configuration, the production start guide can be helpful with that: https://github.com/instructure/canvas-lms/wiki/Production-Start. Also the canvas-lms google group can be helpful in troubleshooting configuration problems: https://groups.google.com/forum/#!forum/canvas-lms-users.

I'm closing this since it is a configuration issue with running canvas. If you need additional help the google group is the best place to ask about this type of question.
