### ISSUE TITLE
Not able to set up the application on my local

### ISSUE THREAD

**Issue by kachroosneha** [instructure/canvas-lms#667]
I had cloned the application on my local. I have all the database set up and all but the assets are not loaded locally and the links displayed are not clickable.

Has someone faced the similar issue or are there some more settings required for the development environment. Please suggest.

**Comment by amulgarg** [comment]
Have you compiled the project assets? If not try running
```
bundle exec rake canvas:compile_assets
```

**Comment by kachroosneha** [comment]
Had run the above step. But there was some issue in that.
  throw new Error('`libsass` bindings not found. Try reinstalling `node-sass`?
Then I did npm rebuild node-sass.
But then the following error was coming:
npm ERR! Linux 3.16.0-30-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "rebuild" "node-sass"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! path /home/sneha/work/code/canvas/node_modules/.bin/node-sass
npm ERR! code EACCES
npm ERR! errno -13

npm ERR! Error: EACCES, unlink '/home/sneha/work/code/canvas/node_modules/.bin/node-sass'
npm ERR!     at Error (native)
npm ERR!  { [Error: EACCES, unlink '/home/sneha/work/code/canvas/node_modules/.bin/node-sass']
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   path: '/home/sneha/work/code/canvas/node_modules/.bin/node-sass' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/sneha/work/code/canvas/npm-debug.log

**Comment by rivernate** [comment]
It looks like the libsass failed due to permission issues, this may help you get squared away: https://docs.npmjs.com/getting-started/fixing-npm-permissions

Also this type of question is usually better asked on our mailing list: https://groups.google.com/forum/#!forum/canvas-lms-users. 

We try to reserve github issues for end user bugs and functionality issues in the app itself. I'm going to close this issue, and suggest if you still have problems to ask on the mailing list. You should see a better response there.

Thanks
