### ISSUE TITLE
Problem with bundle install, rufus-scheduler and delayed_job

### ISSUE THREAD

**Issue by weengs** [instructure/canvas-lms#677]
Hello,

When upgrading canvas, I encounter a problem trying to `bundle install`.
This is what I get:

    Bundler could not find compatible versions for gem "rufus-scheduler":
      In Gemfile:
        delayed_job (>= 0) ruby depends on
          rufus-scheduler (= 2.0.6) ruby

    rufus-scheduler (3.1.2)

I just don't get it. Help !

**Comment by ccutrer** [comment]
Try running `bundle update` instead.

**Comment by weengs** [comment]
OK, I just did a `bundle update` and this is what I get:

    Bundler could not find compatible versions for gem "rufus-scheduler":
      In Gemfile:
        delayed_job (>= 0) ruby depends on
          rufus-scheduler (= 2.0.6) ruby
    
    rufus-scheduler (3.1.2)

**Comment by weengs** [comment]
So this issue isn't closed yet.

**Comment by claydiffrient** [comment]
@weengs A few possible things to check are your ruby and bundler versions.  I can't reproduce this error locally, so it's likely a configuration problem.

We've got a new version of our CONTRIBUTING.md file which will be on our stable branch in the next few weeks but can be seen here: https://github.com/instructure/canvas-lms/blob/master/CONTRIBUTING.md

It goes through better ways to submit issues.  This issue seems to be more of a configuration issue rather than an actual bug with the code base.  You likely will get more information on our mailing list found here: https://groups.google.com/forum/#!forum/canvas-lms-users
