### ISSUE TITLE
One or more prerequisites required to install Kaltura failed

### ISSUE THREAD

**Issue by kachroosneha** [instructure/canvas-lms#686]
I am following https://github.com/instructure/canvas-lms/wiki/Kaltura-setup-instructions for Kaltura installation. Can someone please suggest some solution for the below mentioned error.

sneha@SCS-I82:~/Downloads/kalturaCE_v3.0.0-instructure$ sudo php install.php

Thank you for installing Kaltura Video Platform - Community Edition

A previous installation attempt has been detected, do you want to use the input you provided during you last installation? (Y/n)
> Y

PHP Notice:  Array to string conversion in /home/sneha/Downloads/kalturaCE_v3.0.0-instructure/installer/OsUtils.class.php on line 13
Skipping user input, previous installation input will be used.

Verifing prerequisites

One or more prerequisites required to install Kaltura failed:
   Failed to connect to database 127.0.0.1:3306 user:sneha. Please check the database settings you provided and verify that MySQL is up and running.

Please resolve the issues and run the installation again.

**Comment by ccutrer** [comment]
Thanks for the report. Issues getting Canvas set up and running are better handled on the mailing list or the IRC channel. You can find out about these avenues at https://github.com/instructure/canvas-lms/wiki#getting-help. Additionally, since this is actually a Kaltura issue, not a Canvas issue (the wiki page you mentioned is a "bare minimum to get it working with Canvas"), I'd suggest checking out their community.
