### ISSUE TITLE
Crocodoc plugin + Canvas LMS integration.

### ISSUE THREAD

**Issue by ally1** [instructure/canvas-lms#688]
Hi All,

We used:
Canvas LMS origin/stable/2015-08-08
Crocodoc ver. 1.0.0 

What was done: 
1. We registered on https://app.box.com , created new Box Application and got API Key from there. 
2. Log into our Canvas LMS and Navigate to: "Admin" > "Site Admin" > "Plugins" > "Settings: Crocodoc", type API Key next to the "Crocodoc API Key" field.
3. delayed_jobs_pool was restarted.

We have tried to integrate Crocodoc plugin with Canvas LMS but all attempts were unsuccessful.
Whenever we opened file for annotation we got next alert message: "Crocodoc is still processing this document." and Crocodoc's toolbar did not appear.
Here is screenshot: https://www.dropbox.com/s/0qqq59270hgld2l/2015-09-07_11-35_test2%2C%20SpeedGrader%2C%20test.jpg?dl=0

Does anyone know how to enable Crocodoc plugin to work with Canvas LMS?
Thanks in advance.

**Comment by ccutrer** [comment]
@ally1: thanks for the report. We're aware of the issue. Crocodoc is in a bit of transitionary limbo since the Box acquisition. We're working on a solution, and hope to be able to share it in the coming months. In the meantime, I'm going to close this github issue, since it's being tracked internally.

**Comment by ally1** [comment]
Hi ccutrer,

Thank you for your fast feedback. Will wait the update on this issue.
