### ISSUE TITLE
Table headers and dates translation

### ISSUE THREAD

**Issue by fneto** [instructure/canvas-lms#702]
I'm running Canvas in development env. (followed the quick start guide) and using RAILS_LOAD_ALL_LOCALES=1 so I can change the language to pt-br.

I noticed that dates, table headers and a few other words are not translated. Is this because of missing translations or because setting it up the way I did does not load all translations?

Thanks!

**Comment by lukfugl** [comment]
This is likely (and almost certainly in the case of dates) because those elements are being rendered dynamically through javascript rather than server side. And the localization strings are not available by default to javascript in development mode. There are various ways you can turn it on:

 * Pass an “include_js_translations” query parameter with a truthy value. Requires modifying the URL request by request, so probably not what you want if you want it consistently in pt-BR.
 * Pass an “optimized_js” query parameter with a truthy value. Same as above, but is slightly more general; will cause the concatenated and minified JS (which includes translations) in the public/optimized/ directory to be served.
 * Start your server with a USE_OPTIMIZED_JS=true environment variable. Same effect as the “optimized_js” query parameter, except turns it on by default instead of needing a tweak request by request.

In the last case, you can turn the optimized JS back off on a per-request basis with a "debug_js” query parameter with a truthy value. And for the most complicated combination, you can have USE_OPTIMIZED_JS=true in the server environment, debug_js=1 in the query string, but then turn translations back on with include_js_translations=1. ;)

After typing all that, it seems like it would be a good idea to have a server environment variable such as INCLUDE_JS_TRANSLATIONS=1 to persistently include the JS translations without requiring optimized JS. We don’t have that yet, though, to my knowledge. If you’re interested in adding that and submitting a pull request, the code to modify to check it would be in the `include_js_translations?` method in application_helper.rb.

-- 
Jacob Fugal

On October 6, 2015 at 7:55:01 AM, Felício Moysés Neto (notifications@github.com) wrote:

I'm running Canvas in development env. (followed the quick start guide) and using RAILS_LOAD_ALL_LOCALES=1 so I can change the language to pt-br.

I noticed that dates, table headers and a few other words are not translated. Is this because of missing translations or because setting it up the way I did does not load all translations?

Thanks!
