### ISSUE TITLE
Issue in LTI App

### ISSUE THREAD

**Issue by swapnilv2** [instructure/canvas-lms#723]
Hi,

I am integrating an LTI app which is using OAuth flow to get the access token. While it is working fine with some canvas LMS instances its not working with some canvas instances.
The issue that I am getting while trying to get access token is "client does not have access to specified account".
Once such canvas lms instance where I am getting this error message is https://upgrad.test.instructure.com

Thanks

**Comment by ccutrer** [comment]
When developing an OAuth application against Canvas, you need a Client ID/secret (also known as developer key/secret from Canvas) for _each_ instance of Canvas. Luckily, for Instructure hosted Canvas when we issue a Client ID, it works for all production instances. The URL you mentioned is part of our test environment, which is refreshed from production once every 3 weeks. So if your Client ID is less than 3 weeks old, you can expect it to work on the test instance next week.

**Comment by swapnilv2** [comment]
Thanks for the reply. Yes, I am using the canvas client ID and secret which was generated just by hour ago. Still I am getting the same error. What do you think might be the issue?

**Comment by malthejorgensen** [comment]
We ran into the same error using the [Bitnami Canvas LMS 2016.04.23.03-2 (64-bit)](https://bitnami.com/stack/canvaslms) image. The issue here was that the default setup has a faulty Redis setup (Redis is required for OAuth to work in Canvas).

The user is never notified of the faulty Redis setup as the `ignore_redis_failures`-settings defaults to `true`, and you end up with the `client does not have access to specified account` error.
