### ISSUE TITLE
Discussions don't have an initial timestamp visible

### ISSUE THREAD

**Issue by ctag** [instructure/canvas-lms#725]
When a discussion for a course is created, no posting date is visible to students viewing it. But replies to the discussion *do* have timestamps and dates.

It makes a difference when someone posts a discussion concerning an assignment. Was it posted yesterday before the item was due, or today after it had to be turned in? 

The solution to this should not be requesting immediate emails from Canvas on new discussions and then using the email to determine the initial time and day of posting, which is the only way I can currently think to discern the needed information.

**Comment by simonista** [comment]
Hey @ctag, thanks for reporting this.  Unfortunately, this was done on purpose because the timestamp could often be confusing when teachers had imported old content from other courses to re-use.  I agree that it would be great to show the date, but the logic for figuring out what date to show is complicated:

- if the teacher publishes the discussion, show that date (this is already when it's getting set in the backend)
- if a teacher copies published content from an old course, currently we show the date it was originally published.  maybe it makes sense to show the date it was copied from the old course.  but some schools constantly run content migrations to "sync" content, and we wouldn't want to update the timestamp every time a content migration ran, so maybe only set it if we're copying from an old course and creating a new object in a new course?

Anyway, this is going to need input from our product department since it was a deliberate decision to hide it, so I'd take the suggestion over to our feature suggestion forum: https://community.canvaslms.com/community/ideas/feature-ideas.

Thanks again!
