### ISSUE TITLE
No Audio in BBB throgh Canvas API, works OK when accessing BBB demo directly

### ISSUE THREAD

**Issue by AndranikMarkosyan** [instructure/canvas-lms#753]
While  I integrate the BigBlueButton to Canvas , everything is OK expect for the audio.Audio is not working Mic is not accessible. However audio is working for the BBB demo when  accessing the BBB server directly. and not through the Canvas API. I think the issue is with BBB canvas plugin, which is probably outdated and not fully compatible with BBB latest relise 0.91. please suggest.

**Comment by Kulgar** [comment]
Had same issue, so :+1:

**Comment by tkrause** [comment]
We had the same issue. This was fixed by changing the voiceBridge format in app/models/big_blue_button_conference.rb

:voiceBridge => "%020d" % self.global_id

Also make sure that FreeSwitch for your BigBlueButton instance allows a 20 digit dialplan. 

In /opt/freeswitch/conf/dialplan/bbb_conference.xml:

<condition field="destination_number" expression="(^\d{5}$|^\d{20}$)">

**Comment by jefelon** [comment]
Had same issue,

**Comment by ralphotowo** [comment]
Does anyone have a solution to this issue? I've made those changes above and continue to get the 1004 error when attempting to join with my microphone.

**Comment by jefelon** [comment]
> ¿Alguien tiene una solución a este problema? He realizado los cambios anteriores y sigo recibiendo el error 1004 cuando intento unirme con mi micrófono.

Lo pude recibir después de 2 semanas de investigación, prueba y error, escríbeme jefelon@gmail.com

**Comment by amg-web** [comment]
So much time and nothing fixed till now. Is it a big problem to fix this in plugin?
