### ISSUE TITLE
Unable to add the app

### ISSUE THREAD

**Issue by Hernan-Dev** [instructure/canvas-lms#774]
Hi, we've integrated our tool with Canvas as content providers.
All of our users have gone through the process correctly, but one of our users is unable to include us as an external app.
They keep getting an error saying: "We were unable to add the app"
I've looked in the community and couldn't find anything about it.

Any tips on where to find more information or info on Canvas errors so we can fix this?
Thanks in advance,
H.

**Comment by jenseng** [comment]
@Hernan-Dev as far as I can tell, that error hasn't been reported to Canvas support either, so this may be an isolated issue.

That error message comes from [this file](https://github.com/instructure/canvas-lms/blob/ab5f58635bfe2cd0e3f927ccb9230cc459205340/app/jsx/external_apps/components/AddExternalToolButton.jsx#L73). Could you have the user open up the Chrome (or whatever) dev tools and check the Network tab to see what happens when clicking the button? Presumably there is a 4xx or 5xx error happening. Tracking that down should make it a little more clear what's going on (maybe something is screwy with this user's account?). If you're running your own Canvas, you should also be able to find a corresponding error in your rails logs.
