### ISSUE TITLE
Redirect not happening when creating a new course

### ISSUE THREAD

**Issue by marklocklear** [instructure/canvas-lms#789]
### Summary:
In courses (http://localhost:3000/accounts/1) when I add a new course, the user is not redirected to the course after save.
### Steps to reproduce:
Go to http://localhost:3000/accounts/1 and "Add a New Course". Enter required information and "Add Course. Course is successfully saved, but the user is take back to http://localhost:3000/accounts/1 after the course is saved rather than being redirected to http://localhost:3000/courses/5.

### Expected behavior:
Would expect user to be redirected to the course index page after course creation.
### Additional notes:
Issue seems to be in https://github.com/instructure/canvas-lms/blob/stable/app/controllers/courses_controller.rb#L654 This redirect never gets called.

**Comment by ccutrer** [comment]
This is working as designed. When adding a course from the accounts page, it uses an AJAX call, meaning the response type is JSON (not HTML), and it's the javascript's responsibility to do a redirect if it wants to. In this case, it does not do a redirect, so that an admin can quickly add several courses at a time from that page, without being redirected to them.

**Comment by marklocklear** [comment]
Thanks @ccutrer That helps.
