### ISSUE TITLE
"Remember my authorization" limited to 1 hour for scopes=/auth/userinfo

### ISSUE THREAD

**Issue by cedricboidin** [instructure/canvas-lms#807]
### Summary:

In an authentication workflow with scopes=/auth/userinfo, the "Remember my authorization for this service" checkbox only remembers the authorization for one hour.
### Steps to reproduce:
1. Start a OAuth2 flow with scopes=/auth/userinfo, like https://<canvas-install-url>/login/oauth2/auth?client_id=XXX&response_type=code&redirect_uri=https://example.com/oauth_complete&state=YYY&scopes=/auth/userinfo
2. On the authorization page, check "Remember my authorization for this service" and click "Authorize"
3. One hour later, start a new OAuth2 flow with the same URL
4. The authorization page is shown again 
### Expected behavior:

The authorization page should not show again.
### Additional notes:

Documentation:

> Your application can rely on canvas for a user's identity. During step 1 of the web application flow below, specify the optional scopes parameter as scopes=/auth/userinfo. When the user is asked to grant your application access in step 2 of the web application flow, they will also be given an option to remember their authorization. If they grant access and remember the authorization, Canvas will skip step 2 of the request flow for future requests.

**Comment by ccutrer** [comment]
@cedricboidin I just want to let you know I'm aware of your ticket, but to set expectations that it may not be fixed right away. I'm currently doing lots of work in this area. I've not looked into your issue specifically yet, but just by looking around the code I would not be surprised if such a bug had crept in recently. Ideally I'd like to change Canvas to provide an OpenID Connect compliant way of providing user information, rather than the current one-off protocol that you're having troubles with. At which point this way should continue to function (and hopefully fix the remember access problem), though no longer be documented. But, it will take me a while to build towards that, untangling everything underneath. Which is why I say it may not be fixed right away.

**Comment by cedricboidin** [comment]
Thanks for working on this. Please let me know when it is fixed.
