### ISSUE TITLE
Error while loading plugin CSS

### ISSUE THREAD

**Issue by akshaykumar6** [instructure/canvas-lms#839]
I am working on a Canvas plugin which is at `gems/plugins/my_plugin`. I am trying to load a SCSS file from the plugin which is at `gems/plugins/my_plugin/stylesheets/bundles/my_plugin_style.scss`. I complied assets and I am able to see the compiled file at 
`canvas/public/dist/brandable_css/no_variables/plugins/my_plugin/bundles/my_plugin_style-36c514cc84.css`. 

But while trying to use the CSS file in ruby templates using - 
`<% css_bundle(:my_plugin_style,:plugins => :my_plugin) %>`

I'm getting the error - 

```
RuntimeError (Fingerprint not found. bundles/my_plugin_style new_styles_normal_contrast):
/vagrant/canvas/lib/brandable_css.rb:138:in `cache_for'
/vagrant/canvas/app/helpers/application_helper.rb:297:in `css_url_for'
/vagrant/canvas/app/helpers/application_helper.rb:278:in `block in include_css_bundles'
/vagrant/canvas/app/helpers/application_helper.rb:277:in `map'
/vagrant/canvas/app/helpers/application_helper.rb:277:in `include_css_bundles'
/vagrant/canvas/app/views/layouts/_head.html.erb:26:in `_app_views_layouts__head_html_erb__2927343386945376244_33491840'
/vagrant/canvas/vendor/bundle/ruby/2.1.0/gems/actionpack-4.0.13/lib/action_view/template.rb:143:in `block in render'
/vagrant/canvas/vendor/bundle/ruby/2.1.0/gems/activesupport-4.0.13/lib/active_support/notifications.rb:161:in `instrument'
/vagrant/canvas/vendor/bundle/ruby/2.1.0/gems/actionpack-4.0.13/lib/action_view/template.rb:141:in `render'
/vagrant/canvas/config/initializers/i18n.rb:159:in `render_with_i18nliner_scope'
.
.
.
.
....
```

Why is it throwing this error? What else needs to be done to include it in a ruby template.

**Comment by fred-bict** [comment]
I have the same problem. Any news?

**Comment by fred-bict** [comment]
I have the same problem. Any news?

**Comment by fred-bict** [comment]
Sorry, no issue, just overlooked jammit. For me this helps:
Using jammit_css in views:
– goto gems/plugins/[myplugin]/app/views
– change jammit line in each file
use <% css_bundle :[filename], :plugin => :[myplugin] %> 
instead of <% jammit_css :[filename] %> 

Stylesheets rename file and add line:
– rename stylesheets: gem/plugins/[myplugin]/app/stylesheets/*.css to *.scss
– optional
 @import "components/ui.selectmenu";

Compile assets:
– RAILS_ENV=[env] bundle exec rake canvas:compile_assets
