### ISSUE TITLE
How can I execute "student's Login" process using api ?

### ISSUE THREAD

**Issue by AngeleMM** [instructure/canvas-lms#842]
I have users created from api, when I want to create quiz submissions for created user I get the following response:

```
{
  "status": "forbidden",
  "message": "you are not allowed to participate in this quiz",
  "error_report_id": 272
}
```

but this user already exists in this quiz.

When I loged in from canvas lms and I confirm the authorization after that I am able to create quiz submissions. Can I pass the authorization, if not how I can take authorization with API?

**Comment by ccutrer** [comment]
If you created the user via API, you likely have permission to masquerade as them. So you use the API with your own credentials, and then pass the user you would like to act as: https://canvas.instructure.com/doc/api/file.masquerading.html

**Comment by AngeleMM** [comment]
With this post request `POST https://[my canvas url]/api/v1/accounts/1/users` I creat a user with the following id:  sis_user_id=123452
Then as a result I get a message, that the user is successfully created.

After that I connect this user from Canvas to some course. I create a quiz in the course and add the user to that quiz.

After that, I try to get a quiz submission with the help of this post request: `https://[my canvas url]/api/v1/courses/4/quizzes/3/submissions?as_user_id=sis_user_id:123452`

And get this: 
```
stdClass Object
(
    [status] => forbidden
    [message] => you are not allowed to participate in this quiz
    [error_report_id] => 296
)
```

When I log in Canvas with the new created user and accept the invitation came for a concrete course. Then my quiz submission is created normally.

Is it possible to create a quiz submission for a concrete user without accepting this invitation?

**Comment by simonista** [comment]
Hey @AngeleMM, you're hitting the permission check here: https://github.com/instructure/canvas-lms/blob/stable/app/controllers/quizzes/quiz_submissions_api_controller.rb#L249, which checks a number of different conditions here: https://github.com/instructure/canvas-lms/blob/stable/app/models/quizzes/quiz.rb#L723, but the one that you're asking about is here: https://github.com/instructure/canvas-lms/blob/stable/app/models/course.rb#L1107, specifically, a student must have an active enrollment in the course in order to take the quiz.
