### ISSUE TITLE
Quiz question headers do not appear to students

### ISSUE THREAD

**Issue by ybakos** [instructure/canvas-lms#980]
### Summary:
Customized question headers are saved in the quiz "design" but do not appear to students; instead, the students just see "Question 1," "Question 2", etc.
### Steps to reproduce:

 1. Create a quiz, and add a new question
 2. In the gray box titled Question 1 by default, change it to "Foobar".
 3. Save the question, publish the quiz, and view it as a student.
 4. Note that the "Foobar" header does not appear, but "Question 1" appears instead.

### Expected behavior:
Customized question headers should appear to the students.

### Additional notes:

![screen shot 2017-01-31 at 11 36 38 am](https://cloud.githubusercontent.com/assets/5502/22481337/b896b23e-e7a9-11e6-836e-87b5fd4b35e1.png)
![screen shot 2017-01-31 at 11 33 21 am](https://cloud.githubusercontent.com/assets/5502/22481336/b896a366-e7a9-11e6-8f23-b14201667779.png)

**Comment by tierra** [comment]
Hi @ybakos, thanks for reporting this issue. This is actually working as designed since question titles are meant to be a way for teachers to organize and browse questions in quizzes or question banks. These titles can often contain hints or even full answers to the question being presented to the student. This is why the student sees the numbered questions instead.

This probably isn't entirely clear when building quizzes, and could probably be improved, but we wouldn't ever start displaying those question titles to students at this point since it could compromise the integrity of quizzes.

Thanks for the feedback though.
